{
    "Pacific/Midway":"አጋማሽ",
    "Pacific/Pago_Pago":"ፓጎ ፓጎ",
    "Pacific/Honolulu":"ሆኖሉሉ",
    "America/Juneau":"ጁኒዩ",
    "America/Los_Angeles":"ሎስ አንጀለስ",
    "America/Tijuana":"ቲጁአና",
    "America/Denver":"ዴንቨር",
    "America/Phoenix":"ፊኒክስ",
    "America/Chihuahua":"ቺሁዋውአ",
    "America/Mazatlan":"ማዛትላን",
    "America/Chicago":"ቺካጎ",
    "America/Regina":"ረጂና",
    "America/Mexico_City":"ሜክሲኮ ከተማ",
    "America/Monterrey":"ሞንተርሬይ",
    "America/Guatemala":"ጓቲማላ",
    "America/New_York":"ኒውዮርክ",
    "America/Indiana/Indianapolis":"Indianapolis, Indiana",
    "America/Bogota":"ቦጎታ",
    "America/Lima":"ሊማ",
    "America/Halifax":"ሃሊፋክስ",
    "America/Caracas":"ካራካስ",
    "America/La_Paz":"ላ ፓዝ",
    "America/Santiago":"ሳንቲያጎ",
    "America/St_Johns":"የቅዱስ ዮሃንስ",
    "America/Sao_Paulo":"ሴኦ ፖሎ",
    "America/Argentina/Buenos_Aires":"Buenos Aires, Argentina",
    "America/Guyana":"ጉያና",
    "America/Godthab":"ጋድታብ",
    "Atlantic/South_Georgia":"ደቡብ ጆርጂያ",
    "Atlantic/Azores":"አዞረስ",
    "Atlantic/Cape_Verde":"ኬፕ ቬርደ",
    "Europe/Dublin":"ደብሊን",
    "Europe/London":"ለንደን",
    "Europe/Lisbon":"ሊዝበን",
    "Africa/Casablanca":"ካዛብላንካ",
    "Africa/Monrovia":"ሞንሮቪያ",
    "Etc/UTC":"UTC",
    "Europe/Belgrade":"ቤልግሬድ",
    "Europe/Bratislava":"ብራቲስላቫ",
    "Europe/Budapest":"ቡዳፔስት",
    "Europe/Ljubljana":"ልጁብልጃና",
    "Europe/Prague":"ፕራግ",
    "Europe/Sarajevo":"ሳሪየቮ",
    "Europe/Skopje":"ስኮፕጄ",
    "Europe/Warsaw":"ዋርሳው",
    "Europe/Zagreb":"ዛግረብ",
    "Europe/Brussels":"ብራስል",
    "Europe/Copenhagen":"ኮፐንሃገን",
    "Europe/Madrid":"ማድሪድ",
    "Europe/Paris":"ፓሪስ",
    "Europe/Amsterdam":"አምስተርዳም",
    "Europe/Berlin":"በርሊን",
    "Europe/Rome":"ሮም",
    "Europe/Stockholm":"ስቶክሆልም",
    "Europe/Vienna":"ቪየና",
    "Africa/Algiers":"አልጀርስ",
    "Europe/Bucharest":"ቡካሬስት",
    "Africa/Cairo":"ካይሮ",
    "Europe/Helsinki":"ሄልሲንኪ",
    "Europe/Kiev":"ኪየቭ",
    "Europe/Riga":"ሪጋ",
    "Europe/Sofia":"ሶፊያ",
    "Europe/Tallinn":"ታሊን",
    "Europe/Vilnius":"ቪሊነስ",
    "Europe/Athens":"አቴንስ",
    "Europe/Istanbul":"ኢስታንቡል",
    "Europe/Minsk":"ሚንስክ",
    "Asia/Jerusalem":"እየሩሳሌም",
    "Africa/Harare":"ሃራሬ",
    "Africa/Johannesburg":"ጆሃንስበርግ",
    "Europe/Volgograd":"ቮልጎራድ",
    "Europe/Moscow":"ሞስኮ",
    "Asia/Kuwait":"ኩዌት",
    "Asia/Riyadh":"ሪያድ",
    "Africa/Nairobi":"ናይሮቢ",
    "Asia/Baghdad":"ባግዳድ",
    "Asia/Tehran":"ቴህራን",
    "Asia/Muscat":"ሙስካት",
    "Asia/Baku":"ባኩ",
    "Asia/Tbilisi":"ትብሊሲ",
    "Asia/Yerevan":"ይሬቫን",
    "Asia/Kabul":"ካቡል",
    "Asia/Yekaterinburg":"የካተሪንበርግ",
    "Asia/Karachi":"ካራቺ",
    "Asia/Tashkent":"ታሽኬንት",
    "Asia/Calcutta":"ኮልካታ",
    "Asia/Kathmandu":"Kathmandu",
    "Asia/Dhaka":"ዳካ",
    "Asia/Colombo":"ኮሎምቦ",
    "Asia/Almaty":"አልማትይ",
    "Asia/Novosibirsk":"ኖቮሲቢሪስክ",
    "Asia/Rangoon":"ራንጉን",
    "Asia/Bangkok":"ባንኮክ",
    "Asia/Jakarta":"ጃካርታ",
    "Asia/Krasnoyarsk":"ክራስኖያርስክ",
    "Asia/Shanghai":"ሸንጋይ",
    "Asia/Chongqing":"ቾንግኪንግ",
    "Asia/Hong_Kong":"ሆንግ ኮንግ",
    "Asia/Urumqi":"ኡሩምኪ",
    "Asia/Kuala_Lumpur":"ኩዋላ ላምፑር",
    "Asia/Singapore":"ሲንጋፖር",
    "Asia/Taipei":"ታይፓይ",
    "Australia/Perth":"ፐርዝ",
    "Asia/Irkutsk":"ኢርኩትስክ",
    "Asia/Ulaanbaatar":"ኡላአንባአታር",
    "Asia/Seoul":"ሴኦል",
    "Asia/Tokyo":"ቶኪዮ",
    "Asia/Yakutsk":"ያኩትስክ",
    "Australia/Darwin":"ዳርዊን",
    "Australia/Adelaide":"አዴሌእድ",
    "Australia/Melbourne":"ሜልቦርን",
    "Australia/Sydney":"ሲድኒ",
    "Australia/Brisbane":"ብሪስቤን",
    "Australia/Hobart":"ሆባርት",
    "Asia/Vladivostok":"ቭላዲቮስቶክ",
    "Pacific/Guam":"ጉአም",
    "Pacific/Port_Moresby":"ፖርት ሞሬስባይ",
    "Asia/Magadan":"ማጋዳን",
    "Pacific/Noumea":"ናኦሚአ",
    "Pacific/Fiji":"ፊጂ",
    "Asia/Kamchatka":"ካምቻትካ",
    "Pacific/Majuro":"ማጁሩ",
    "Pacific/Auckland":"ኦክላንድ",
    "Pacific/Tongatapu":"ቶንጋታፑ"
}