var ar_001_cldr_timezones_hash = {
    "Pacific/Midway":"ميدواي",
    "Pacific/Pago_Pago":"باغو باغو",
    "Pacific/Honolulu":"هونولولو",
    "America/Juneau":"جوني",
    "America/Los_Angeles":"لوس انجلوس",
    "America/Tijuana":"تيخوانا",
    "America/Denver":"دنفر",
    "America/Phoenix":"فينكس",
    "America/Chihuahua":"تشيواوا",
    "America/Mazatlan":"مازاتلان",
    "America/Chicago":"شيكاغو",
    "America/Regina":"ريجينا",
    "America/Mexico_City":"مدينة المكسيك",
    "America/Monterrey":"مونتيري",
    "America/Guatemala":"غواتيمالا",
    "America/New_York":"نيويورك",
    "America/Indiana/Indianapolis":"Indianapolis, Indiana",
    "America/Bogota":"بوغوتا",
    "America/Lima":"ليما",
    "America/Halifax":"هاليفاكس",
    "America/Caracas":"کاراکاس",
    "America/La_Paz":"لا باز",
    "America/Santiago":"سانتياغو",
    "America/St_Johns":"St. John’s",
    "America/Sao_Paulo":"ساو باولو",
    "America/Argentina/Buenos_Aires":"Buenos Aires, Argentina",
    "America/Guyana":"غيانا",
    "America/Godthab":"غودثاب",
    "Atlantic/South_Georgia":"جنوب جورجيا",
    "Atlantic/Azores":"أزورس",
    "Atlantic/Cape_Verde":"الرأس الأخضر",
    "Europe/Dublin":"دبلن",
    "Europe/London":"لندن",
    "Europe/Lisbon":"لشبونة",
    "Africa/Casablanca":"الدار البيضاء",
    "Africa/Monrovia":"مونروفيا",
    "Etc/UTC":"UTC",
    "Europe/Belgrade":"بلغراد",
    "Europe/Bratislava":"براتيسلافا",
    "Europe/Budapest":"بودابست",
    "Europe/Ljubljana":"ليوبليانا",
    "Europe/Prague":"براغ",
    "Europe/Sarajevo":"سراييفو",
    "Europe/Skopje":"سكوبي",
    "Europe/Warsaw":"وارسو",
    "Europe/Zagreb":"زغرب",
    "Europe/Brussels":"بروکسل",
    "Europe/Copenhagen":"كوبنهاغن",
    "Europe/Madrid":"مدريد",
    "Europe/Paris":"باريس",
    "Europe/Amsterdam":"أمستردام",
    "Europe/Berlin":"برلين",
    "Europe/Rome":"روما",
    "Europe/Stockholm":"ستوكهولم",
    "Europe/Vienna":"فيينا",
    "Africa/Algiers":"الجزائر",
    "Europe/Bucharest":"بوخارست",
    "Africa/Cairo":"القاهرة",
    "Europe/Helsinki":"هلسنكي",
    "Europe/Kiev":"كييف",
    "Europe/Riga":"ريغا",
    "Europe/Sofia":"صوفیا",
    "Europe/Tallinn":"تالین",
    "Europe/Vilnius":"فيلنيوس",
    "Europe/Athens":"أثينا",
    "Europe/Istanbul":"إسطنبول",
    "Europe/Minsk":"مینسك",
    "Asia/Jerusalem":"القدس",
    "Africa/Harare":"هراري",
    "Africa/Johannesburg":"جوهانسبرغ",
    "Europe/Volgograd":"فولوجراد",
    "Europe/Moscow":"موسكو",
    "Asia/Kuwait":"الكويت",
    "Asia/Riyadh":"الرياض",
    "Africa/Nairobi":"نیروبي",
    "Asia/Baghdad":"بغداد",
    "Asia/Tehran":"طهران",
    "Asia/Muscat":"مسقط",
    "Asia/Baku":"باكو",
    "Asia/Tbilisi":"تبليسي",
    "Asia/Yerevan":"يريفان",
    "Asia/Kabul":"كابول",
    "Asia/Yekaterinburg":"يكاترنبيرج",
    "Asia/Karachi":"كراتشي",
    "Asia/Tashkent":"طشقند",
    "Asia/Calcutta":"Kolkata",
    "Asia/Kathmandu":"Kathmandu",
    "Asia/Dhaka":"دكا",
    "Asia/Colombo":"كولومبو",
    "Asia/Almaty":"ألماتي",
    "Asia/Novosibirsk":"نوفوسبيرسك",
    "Asia/Rangoon":"رانغون",
    "Asia/Bangkok":"بانكوك",
    "Asia/Jakarta":"جاكرتا",
    "Asia/Krasnoyarsk":"كراسنويارسك",
    "Asia/Shanghai":"شنغهاي",
    "Asia/Chongqing":"تشونجكينج",
    "Asia/Hong_Kong":"هونغ كونغ",
    "Asia/Urumqi":"أرومكي",
    "Asia/Kuala_Lumpur":"کوالا لامبور",
    "Asia/Singapore":"سنغافورة",
    "Asia/Taipei":"تايبيه",
    "Australia/Perth":"برثا",
    "Asia/Irkutsk":"ايركيتسك",
    "Asia/Ulaanbaatar":"آلانباتار",
    "Asia/Seoul":"سول",
    "Asia/Tokyo":"طوكيو",
    "Asia/Yakutsk":"ياكتسك",
    "Australia/Darwin":"دارون",
    "Australia/Adelaide":"استراليا(توقيت أدليادا",
    "Australia/Melbourne":"ميلبورن",
    "Australia/Sydney":"سيدني",
    "Australia/Brisbane":"برسيبان",
    "Australia/Hobart":"هوبارت",
    "Asia/Vladivostok":"فلاديفوستك",
    "Pacific/Guam":"غوام",
    "Pacific/Port_Moresby":"بور مورسبي",
    "Asia/Magadan":"مجادن",
    "Pacific/Noumea":"نوميا",
    "Pacific/Fiji":"فيجي",
    "Asia/Kamchatka":"كامتشاتكا",
    "Pacific/Majuro":"ماجورو",
    "Pacific/Auckland":"أوكلاند",
    "Pacific/Tongatapu":"تونغاتابو"
}