{
    "Pacific/Midway":"о. Мидуей",
    "Pacific/Pago_Pago":"Паго Паго",
    "Pacific/Honolulu":"Хонолулу",
    "America/Juneau":"Джуно",
    "America/Los_Angeles":"Лос Анжелис",
    "America/Tijuana":"Тихуана",
    "America/Denver":"Денвър",
    "America/Phoenix":"Финикс",
    "America/Chihuahua":"Чиуауа",
    "America/Mazatlan":"Мацатлан",
    "America/Chicago":"Чикаго",
    "America/Regina":"Регина",
    "America/Mexico_City":"Мексико",
    "America/Monterrey":"Монтерей",
    "America/Guatemala":"Гватемала",
    "America/New_York":"Ню Йорк",
    "America/Indiana/Indianapolis":"Indianapolis, Indiana",
    "America/Bogota":"Богота",
    "America/Lima":"Лима",
    "America/Halifax":"Халифакс",
    "America/Caracas":"Каракас",
    "America/La_Paz":"Ла Пас",
    "America/Santiago":"Сантиаго",
    "America/St_Johns":"St. John’s",
    "America/Sao_Paulo":"Сао Пауло",
    "America/Argentina/Buenos_Aires":"Buenos Aires, Argentina",
    "America/Guyana":"Гвиана",
    "America/Godthab":"Готхоб",
    "Atlantic/South_Georgia":"Южна Джорджия",
    "Atlantic/Azores":"Азорски о-ви",
    "Atlantic/Cape_Verde":"Кабо Верде",
    "Europe/Dublin":"Дъблин",
    "Europe/London":"Лондон",
    "Europe/Lisbon":"Лисабон",
    "Africa/Casablanca":"Казабланка",
    "Africa/Monrovia":"Монровия",
    "Etc/UTC":"UTC",
    "Europe/Belgrade":"Белград",
    "Europe/Bratislava":"Братислава",
    "Europe/Budapest":"Будапеща",
    "Europe/Ljubljana":"Любляна",
    "Europe/Prague":"Прага",
    "Europe/Sarajevo":"Сараево",
    "Europe/Skopje":"Скопие",
    "Europe/Warsaw":"Варшава",
    "Europe/Zagreb":"Загреб",
    "Europe/Brussels":"Брюксел",
    "Europe/Copenhagen":"Копенхаген",
    "Europe/Madrid":"Мадрид",
    "Europe/Paris":"Париж",
    "Europe/Amsterdam":"Амстердам",
    "Europe/Berlin":"Берлин",
    "Europe/Rome":"Рим",
    "Europe/Stockholm":"Стокхолм",
    "Europe/Vienna":"Виена",
    "Africa/Algiers":"Алжир",
    "Europe/Bucharest":"Букурещ",
    "Africa/Cairo":"Кайро",
    "Europe/Helsinki":"Хелзинки",
    "Europe/Kiev":"Киев",
    "Europe/Riga":"Рига",
    "Europe/Sofia":"София",
    "Europe/Tallinn":"Талин",
    "Europe/Vilnius":"Вилнюс",
    "Europe/Athens":"Атина",
    "Europe/Istanbul":"Истанбул",
    "Europe/Minsk":"Минск",
    "Asia/Jerusalem":"Йерусалим",
    "Africa/Harare":"Хараре",
    "Africa/Johannesburg":"Йоханесбург",
    "Europe/Volgograd":"Волгоград",
    "Europe/Moscow":"Москва",
    "Asia/Kuwait":"Кувейт",
    "Asia/Riyadh":"Рияд",
    "Africa/Nairobi":"Найроби",
    "Asia/Baghdad":"Багдад",
    "Asia/Tehran":"Техеран",
    "Asia/Muscat":"Мускат",
    "Asia/Baku":"Баку",
    "Asia/Tbilisi":"Тбилиси",
    "Asia/Yerevan":"Ереван",
    "Asia/Kabul":"Кабул",
    "Asia/Yekaterinburg":"Екатерининбург",
    "Asia/Karachi":"Карачи",
    "Asia/Tashkent":"Ташкент",
    "Asia/Calcutta":"Kolkata",
    "Asia/Kathmandu":"Kathmandu",
    "Asia/Dhaka":"Дака",
    "Asia/Colombo":"Коломбо",
    "Asia/Almaty":"Алма Ата",
    "Asia/Novosibirsk":"Новосибирск",
    "Asia/Rangoon":"Рангун",
    "Asia/Bangkok":"Банкок",
    "Asia/Jakarta":"Джакарта",
    "Asia/Krasnoyarsk":"Красноярск",
    "Asia/Shanghai":"Шанхай",
    "Asia/Chongqing":"Чунцин",
    "Asia/Hong_Kong":"Хонконг",
    "Asia/Urumqi":"Урумчи",
    "Asia/Kuala_Lumpur":"Куала Лумпур",
    "Asia/Singapore":"Сингапур",
    "Asia/Taipei":"Тайпей",
    "Australia/Perth":"Пърт",
    "Asia/Irkutsk":"Иркутск",
    "Asia/Ulaanbaatar":"Уланбатор",
    "Asia/Seoul":"Сеул",
    "Asia/Tokyo":"Токио",
    "Asia/Yakutsk":"Якутск",
    "Australia/Darwin":"Даруин",
    "Australia/Adelaide":"Аделаида",
    "Australia/Melbourne":"Мелбърн",
    "Australia/Sydney":"Сидни",
    "Australia/Brisbane":"Бризбейн",
    "Australia/Hobart":"Хоубарт",
    "Asia/Vladivostok":"Владивосток",
    "Pacific/Guam":"Гуам",
    "Pacific/Port_Moresby":"Порт Морсби",
    "Asia/Magadan":"Магадан",
    "Pacific/Noumea":"Нумеа",
    "Pacific/Fiji":"Фиджи",
    "Asia/Kamchatka":"п-в Камчатка",
    "Pacific/Majuro":"Мажуро",
    "Pacific/Auckland":"Окланд",
    "Pacific/Tongatapu":"Тонгатапу"
}