{
    "Pacific/Midway":"Midway",
    "Pacific/Pago_Pago":"Pago Pago",
    "Pacific/Honolulu":"Honolulu",
    "America/Juneau":"Juneau",
    "America/Los_Angeles":"Los Angeles",
    "America/Tijuana":"Tijuana",
    "America/Denver":"Denver",
    "America/Phoenix":"Phoenix",
    "America/Chihuahua":"Chihuahua",
    "America/Mazatlan":"Mazatlán",
    "America/Chicago":"Chicago",
    "America/Regina":"Regina",
    "America/Mexico_City":"Ciudad de México",
    "America/Monterrey":"Monterrey",
    "America/Guatemala":"Guatemala",
    "America/New_York":"New York",
    "America/Indiana/Indianapolis":"Indianapolis, Indiana",
    "America/Bogota":"Bogotá",
    "America/Lima":"Lima",
    "America/Halifax":"Halifax",
    "America/Caracas":"Caracas",
    "America/La_Paz":"La Paz",
    "America/Santiago":"Santiago",
    "America/St_Johns":"St. John's",
    "America/Sao_Paulo":"São Paulo",
    "America/Argentina/Buenos_Aires":"Buenos Aires, Argentina",
    "America/Guyana":"Guyana",
    "America/Godthab":"Nuuk",
    "Atlantic/South_Georgia":"Etelä-Georgia",
    "Atlantic/Azores":"Azorit",
    "Atlantic/Cape_Verde":"Kap Verde",
    "Europe/Dublin":"Dublin",
    "Europe/London":"Lontoo",
    "Europe/Lisbon":"Lissabon",
    "Africa/Casablanca":"Casablanca",
    "Africa/Monrovia":"Monrovia",
    "Etc/UTC":"UTC",
    "Europe/Belgrade":"Belgrad",
    "Europe/Bratislava":"Bratislava",
    "Europe/Budapest":"Budapest",
    "Europe/Ljubljana":"Ljubljana",
    "Europe/Prague":"Praha",
    "Europe/Sarajevo":"Sarajevo",
    "Europe/Skopje":"Skopje",
    "Europe/Warsaw":"Varsova",
    "Europe/Zagreb":"Zagreb",
    "Europe/Brussels":"Bryssel",
    "Europe/Copenhagen":"Kööpenhamina",
    "Europe/Madrid":"Madrid",
    "Europe/Paris":"Pariisi",
    "Europe/Amsterdam":"Amsterdam",
    "Europe/Berlin":"Berliini",
    "Europe/Rome":"Rooma",
    "Europe/Stockholm":"Tukholma",
    "Europe/Vienna":"Wien",
    "Africa/Algiers":"Alger",
    "Europe/Bucharest":"Bukarest",
    "Africa/Cairo":"Kairo",
    "Europe/Helsinki":"Helsinki",
    "Europe/Kiev":"Kiova",
    "Europe/Riga":"Riika",
    "Europe/Sofia":"Sofia",
    "Europe/Tallinn":"Tallinna",
    "Europe/Vilnius":"Vilna",
    "Europe/Athens":"Ateena",
    "Europe/Istanbul":"Istanbul",
    "Europe/Minsk":"Minsk",
    "Asia/Jerusalem":"Jerusalem",
    "Africa/Harare":"Harare",
    "Africa/Johannesburg":"Johannesburg",
    "Europe/Volgograd":"Volgograd",
    "Europe/Moscow":"Moskova",
    "Asia/Kuwait":"Kuwait",
    "Asia/Riyadh":"Riad",
    "Africa/Nairobi":"Nairobi",
    "Asia/Baghdad":"Bagdad",
    "Asia/Tehran":"Teheran",
    "Asia/Muscat":"Muscat",
    "Asia/Baku":"Baku",
    "Asia/Tbilisi":"Tbilisi",
    "Asia/Yerevan":"Jerevan",
    "Asia/Kabul":"Kabul",
    "Asia/Yekaterinburg":"Jekaterinburg",
    "Asia/Karachi":"Karachi",
    "Asia/Tashkent":"Taškent",
    "Asia/Calcutta":"Kalkutta",
    "Asia/Kathmandu":"Kathmandu",
    "Asia/Dhaka":"Dhaka",
    "Asia/Colombo":"Colombo",
    "Asia/Almaty":"Almaty",
    "Asia/Novosibirsk":"Novosibirsk",
    "Asia/Rangoon":"Yangon",
    "Asia/Bangkok":"Bangkok",
    "Asia/Jakarta":"Jakarta",
    "Asia/Krasnoyarsk":"Krasnojarsk",
    "Asia/Shanghai":"Shanghai",
    "Asia/Chongqing":"Chongqing",
    "Asia/Hong_Kong":"Hongkong",
    "Asia/Urumqi":"Urumqi",
    "Asia/Kuala_Lumpur":"Kuala Lumpur",
    "Asia/Singapore":"Singapore",
    "Asia/Taipei":"Taipei",
    "Australia/Perth":"Perth",
    "Asia/Irkutsk":"Irkutsk",
    "Asia/Ulaanbaatar":"Ulaanbaatar",
    "Asia/Seoul":"Soul",
    "Asia/Tokyo":"Tokio",
    "Asia/Yakutsk":"Jakutsk",
    "Australia/Darwin":"Darwin",
    "Australia/Adelaide":"Adelaide",
    "Australia/Melbourne":"Melbourne",
    "Australia/Sydney":"Sydney",
    "Australia/Brisbane":"Brisbane",
    "Australia/Hobart":"Hobart",
    "Asia/Vladivostok":"Vladivostok",
    "Pacific/Guam":"Guam",
    "Pacific/Port_Moresby":"Port Moresby",
    "Asia/Magadan":"Magadan",
    "Pacific/Noumea":"Nouméa",
    "Pacific/Fiji":"Fidži",
    "Asia/Kamchatka":"Kamtšatka",
    "Pacific/Majuro":"Majuro",
    "Pacific/Auckland":"Auckland",
    "Pacific/Tongatapu":"Tongatapu"
}