{
    "Pacific/Midway":"Midway",
    "Pacific/Pago_Pago":"Pago Pago",
    "Pacific/Honolulu":"Honolulu",
    "America/Juneau":"Juneau",
    "America/Los_Angeles":"Los Angeles",
    "America/Tijuana":"Tijuana",
    "America/Denver":"Denver",
    "America/Phoenix":"Phoenix",
    "America/Chihuahua":"Chihuahua",
    "America/Mazatlan":"Mazatlan",
    "America/Chicago":"Chicago",
    "America/Regina":"Regina",
    "America/Mexico_City":"Mexico City",
    "America/Monterrey":"Monterrey",
    "America/Guatemala":"Guatemala",
    "America/New_York":"Gnove York",
    "America/Indiana/Indianapolis":"Indianapolis, Indiana",
    "America/Bogota":"Bogota",
    "America/Lima":"Lima",
    "America/Halifax":"Halifax",
    "America/Caracas":"Caracas",
    "America/La_Paz":"La Paz",
    "America/Santiago":"Santiago",
    "America/St_Johns":"St. John’s",
    "America/Sao_Paulo":"San Pauli dal Brasîl",
    "America/Argentina/Buenos_Aires":"Buenos Aires, Argentina",
    "America/Guyana":"Guyana",
    "America/Godthab":"Godthab",
    "Atlantic/South_Georgia":"South Georgia",
    "Atlantic/Azores":"Azoris",
    "Atlantic/Cape_Verde":"Cape Verde",
    "Europe/Dublin":"Dublin",
    "Europe/London":"London",
    "Europe/Lisbon":"Lisbone",
    "Africa/Casablanca":"Casablanca",
    "Africa/Monrovia":"Monrovia",
    "Etc/UTC":"UTC",
    "Europe/Belgrade":"Belgrât",
    "Europe/Bratislava":"Bratislava",
    "Europe/Budapest":"Budapest",
    "Europe/Ljubljana":"Lubiane",
    "Europe/Prague":"Praghe",
    "Europe/Sarajevo":"Sarajevo",
    "Europe/Skopje":"Skopje",
    "Europe/Warsaw":"Warsaw",
    "Europe/Zagreb":"Zagreb",
    "Europe/Brussels":"Brussels",
    "Europe/Copenhagen":"Copenhagen",
    "Europe/Madrid":"Madrid",
    "Europe/Paris":"Paris",
    "Europe/Amsterdam":"Amsterdam",
    "Europe/Berlin":"Berlin",
    "Europe/Rome":"Rome",
    "Europe/Stockholm":"Stockholm",
    "Europe/Vienna":"Viene",
    "Africa/Algiers":"Algiers",
    "Europe/Bucharest":"Bucharest",
    "Africa/Cairo":"Cairo",
    "Europe/Helsinki":"Helsinki",
    "Europe/Kiev":"Kiev",
    "Europe/Riga":"Riga",
    "Europe/Sofia":"Sofia",
    "Europe/Tallinn":"Tallinn",
    "Europe/Vilnius":"Vilnius",
    "Europe/Athens":"Athens",
    "Europe/Istanbul":"Istanbul",
    "Europe/Minsk":"Minsk",
    "Asia/Jerusalem":"Jerusalem",
    "Africa/Harare":"Harare",
    "Africa/Johannesburg":"Johannesburg",
    "Europe/Volgograd":"Volgograd",
    "Europe/Moscow":"Mosche",
    "Asia/Kuwait":"Kuwait",
    "Asia/Riyadh":"Riyadh",
    "Africa/Nairobi":"Nairobi",
    "Asia/Baghdad":"Baghdad",
    "Asia/Tehran":"Tehran",
    "Asia/Muscat":"Muscat",
    "Asia/Baku":"Baku",
    "Asia/Tbilisi":"Tbilisi",
    "Asia/Yerevan":"Yerevan",
    "Asia/Kabul":"Kabul",
    "Asia/Yekaterinburg":"Yekaterinburg",
    "Asia/Karachi":"Karachi",
    "Asia/Tashkent":"Tashkent",
    "Asia/Calcutta":"Kolkata",
    "Asia/Kathmandu":"Kathmandu",
    "Asia/Dhaka":"Dhaka",
    "Asia/Colombo":"Colombo",
    "Asia/Almaty":"Almaty",
    "Asia/Novosibirsk":"Novosibirsk",
    "Asia/Rangoon":"Rangoon",
    "Asia/Bangkok":"Bangkok",
    "Asia/Jakarta":"Jakarta",
    "Asia/Krasnoyarsk":"Krasnoyarsk",
    "Asia/Shanghai":"Shanghai",
    "Asia/Chongqing":"Chongqing",
    "Asia/Hong_Kong":"Hong Kong",
    "Asia/Urumqi":"Urumqi",
    "Asia/Kuala_Lumpur":"Kuala Lumpur",
    "Asia/Singapore":"Singapore",
    "Asia/Taipei":"Taipei",
    "Australia/Perth":"Perth",
    "Asia/Irkutsk":"Irkutsk",
    "Asia/Ulaanbaatar":"Ulaanbaatar",
    "Asia/Seoul":"Seoul",
    "Asia/Tokyo":"Tokyo",
    "Asia/Yakutsk":"Yakutsk",
    "Australia/Darwin":"Darwin",
    "Australia/Adelaide":"Adelaide",
    "Australia/Melbourne":"Melbourne",
    "Australia/Sydney":"Sydney",
    "Australia/Brisbane":"Brisbane",
    "Australia/Hobart":"Hobart",
    "Asia/Vladivostok":"Vladivostok",
    "Pacific/Guam":"Guam",
    "Pacific/Port_Moresby":"Port Moresby",
    "Asia/Magadan":"Magadan",
    "Pacific/Noumea":"Noumea",
    "Pacific/Fiji":"Fiji",
    "Asia/Kamchatka":"Kamchatka",
    "Pacific/Majuro":"Majuro",
    "Pacific/Auckland":"Auckland",
    "Pacific/Tongatapu":"Tongatapu"
}