{
    "Pacific/Midway":"मिडवे",
    "Pacific/Pago_Pago":"पागो पागो",
    "Pacific/Honolulu":"हॉनॉलुलु",
    "America/Juneau":"जुनेऔ",
    "America/Los_Angeles":"लोस एंजिलेस",
    "America/Tijuana":"टिज्यूआना",
    "America/Denver":"डेनवर",
    "America/Phoenix":"फोनिक्स",
    "America/Chihuahua":"चिहुआहुआ",
    "America/Mazatlan":"म्जाटलान",
    "America/Chicago":"शिकागो",
    "America/Regina":"रेजिना",
    "America/Mexico_City":"मेक्सिको सिटी",
    "America/Monterrey":"मोंटेरे",
    "America/Guatemala":"ग्वाटेमाला",
    "America/New_York":"न्यूयार्क",
    "America/Indiana/Indianapolis":"Indianapolis, Indiana",
    "America/Bogota":"बोगोटा",
    "America/Lima":"लीमा",
    "America/Halifax":"हेलिफेक्स",
    "America/Caracas":"काराकस",
    "America/La_Paz":"ला पाज़",
    "America/Santiago":"सैनटियागो",
    "America/St_Johns":"सेंट जोंस",
    "America/Sao_Paulo":"साओ पॉलो",
    "America/Argentina/Buenos_Aires":"Buenos Aires, Argentina",
    "America/Guyana":"गयाना",
    "America/Godthab":"गॉटहॉप",
    "Atlantic/South_Georgia":"दक्षिण जॉर्जिया",
    "Atlantic/Azores":"अज़ोरस",
    "Atlantic/Cape_Verde":"केप वर्दे",
    "Europe/Dublin":"डबलिन",
    "Europe/London":"लंदन",
    "Europe/Lisbon":"लिस्बन",
    "Africa/Casablanca":"कासाब्लांका",
    "Africa/Monrovia":"मोनरोविया",
    "Etc/UTC":"UTC",
    "Europe/Belgrade":"बेलग्रेड",
    "Europe/Bratislava":"ब्रतिस्लावा",
    "Europe/Budapest":"बुडापेस्ट",
    "Europe/Ljubljana":"लुबलियाना",
    "Europe/Prague":"प्राग",
    "Europe/Sarajevo":"साराजेवो",
    "Europe/Skopje":"स्कोप्ये",
    "Europe/Warsaw":"वॉरसॉ",
    "Europe/Zagreb":"ज़ाग्रेब",
    "Europe/Brussels":"ब्रुसेल्स",
    "Europe/Copenhagen":"कोपेनहेगेन",
    "Europe/Madrid":"मैड्रिड",
    "Europe/Paris":"पेरिस",
    "Europe/Amsterdam":"एम्स्टर्डम",
    "Europe/Berlin":"बर्लिन",
    "Europe/Rome":"रोम",
    "Europe/Stockholm":"स्टॉकहोम",
    "Europe/Vienna":"विएना",
    "Africa/Algiers":"अल्जीयर्स",
    "Europe/Bucharest":"बुख़ारेस्ट",
    "Africa/Cairo":"कैरो",
    "Europe/Helsinki":"हेलसिंकी",
    "Europe/Kiev":"कीव",
    "Europe/Riga":"रीगा",
    "Europe/Sofia":"सोफ़िया",
    "Europe/Tallinn":"तालिन्न",
    "Europe/Vilnius":"विल्नियस",
    "Europe/Athens":"एथेंस",
    "Europe/Istanbul":"इस्तांबुल",
    "Europe/Minsk":"मिन्स्क",
    "Asia/Jerusalem":"यरूशलम",
    "Africa/Harare":"हरारे",
    "Africa/Johannesburg":"जोहांसबर्ग",
    "Europe/Volgograd":"वोल्गोग्रेड",
    "Europe/Moscow":"मॉस्को",
    "Asia/Kuwait":"कुवैत",
    "Asia/Riyadh":"रियाद",
    "Africa/Nairobi":"नैरोबी",
    "Asia/Baghdad":"बग़दाद",
    "Asia/Tehran":"तेहरान",
    "Asia/Muscat":"मस्कट",
    "Asia/Baku":"बाकु",
    "Asia/Tbilisi":"टिबलिसी",
    "Asia/Yerevan":"येरेवान",
    "Asia/Kabul":"काबुल",
    "Asia/Yekaterinburg":"येकांतिरिंबर्ग",
    "Asia/Karachi":"कराची",
    "Asia/Tashkent":"ताशकंद",
    "Asia/Calcutta":"कोलकाता",
    "Asia/Kathmandu":"Kathmandu",
    "Asia/Dhaka":"ढाका",
    "Asia/Colombo":"कोलम्बो",
    "Asia/Almaty":"अल्माटी",
    "Asia/Novosibirsk":"नॉवोसिविर्स्क्",
    "Asia/Rangoon":"रंगून",
    "Asia/Bangkok":"बैंकॉक",
    "Asia/Jakarta":"जकार्ता",
    "Asia/Krasnoyarsk":"क्रास्नोयार्स्क",
    "Asia/Shanghai":"शंघाई",
    "Asia/Chongqing":"चोंग्पिंग",
    "Asia/Hong_Kong":"हांग कांग",
    "Asia/Urumqi":"उरम्ची",
    "Asia/Kuala_Lumpur":"कुआलालम्पुर",
    "Asia/Singapore":"सिंगापुर",
    "Asia/Taipei":"ताईपेई",
    "Australia/Perth":"पर्थ",
    "Asia/Irkutsk":"ईर्कुत्स्क",
    "Asia/Ulaanbaatar":"उलानबाटर",
    "Asia/Seoul":"सिओल",
    "Asia/Tokyo":"टोक्यो",
    "Asia/Yakutsk":"याकूत्स्क",
    "Australia/Darwin":"डार्विन्",
    "Australia/Adelaide":"एडिलेड",
    "Australia/Melbourne":"मेलबोर्न",
    "Australia/Sydney":"सिडनी",
    "Australia/Brisbane":"ब्रिसबेन",
    "Australia/Hobart":"होबर्ट्",
    "Asia/Vladivostok":"ब्लाडिवोस्टोक",
    "Pacific/Guam":"गुआम",
    "Pacific/Port_Moresby":"पोर्ट मोरेस्बी",
    "Asia/Magadan":"मगादन",
    "Pacific/Noumea":"नौमिया",
    "Pacific/Fiji":"फ़िजी",
    "Asia/Kamchatka":"कमचटका",
    "Pacific/Majuro":"माजुरो",
    "Pacific/Auckland":"ऑकलैंड",
    "Pacific/Tongatapu":"टोंगाटापु"
}