{
    "Pacific/Midway":"Midway",
    "Pacific/Pago_Pago":"Pago Pago",
    "Pacific/Honolulu":"Honolulu",
    "America/Juneau":"Juneau",
    "America/Los_Angeles":"Los Angeles",
    "America/Tijuana":"Tijuana",
    "America/Denver":"Denver",
    "America/Phoenix":"Phoenix",
    "America/Chihuahua":"Chihuahua",
    "America/Mazatlan":"Mazatlan",
    "America/Chicago":"Chicago",
    "America/Regina":"Regina",
    "America/Mexico_City":"Mexico City",
    "America/Monterrey":"Monterrey",
    "America/Guatemala":"Gvatemala",
    "America/New_York":"New York",
    "America/Indiana/Indianapolis":"Indianapolis, Indiana",
    "America/Bogota":"Bogota",
    "America/Lima":"Lima",
    "America/Halifax":"Halifax",
    "America/Caracas":"Caracas",
    "America/La_Paz":"La Paz",
    "America/Santiago":"Santiago",
    "America/St_Johns":"St. John’s",
    "America/Sao_Paulo":"Sao Paulo",
    "America/Argentina/Buenos_Aires":"Buenos Aires, Argentina",
    "America/Guyana":"Gvajana",
    "America/Godthab":"Godthab",
    "Atlantic/South_Georgia":"South Georgia",
    "Atlantic/Azores":"Azorski otoci",
    "Atlantic/Cape_Verde":"Zelenortski Otoci",
    "Europe/Dublin":"Dublin",
    "Europe/London":"London",
    "Europe/Lisbon":"Lisabon",
    "Africa/Casablanca":"Casablanca",
    "Africa/Monrovia":"Monrovia",
    "Etc/UTC":"UTC",
    "Europe/Belgrade":"Belgrade",
    "Europe/Bratislava":"Bratislava",
    "Europe/Budapest":"Budimpešta",
    "Europe/Ljubljana":"Ljubljana",
    "Europe/Prague":"Prague",
    "Europe/Sarajevo":"Sarajevo",
    "Europe/Skopje":"Skopje",
    "Europe/Warsaw":"Varšava",
    "Europe/Zagreb":"Zagreb",
    "Europe/Brussels":"Brussels",
    "Europe/Copenhagen":"Copenhagen",
    "Europe/Madrid":"Madrid",
    "Europe/Paris":"Pariz",
    "Europe/Amsterdam":"Amsterdam",
    "Europe/Berlin":"Berlin",
    "Europe/Rome":"Rim",
    "Europe/Stockholm":"Stockholm",
    "Europe/Vienna":"Beč",
    "Africa/Algiers":"Alžir",
    "Europe/Bucharest":"Bukurešt",
    "Africa/Cairo":"Cairo",
    "Europe/Helsinki":"Helsinki",
    "Europe/Kiev":"Kijev",
    "Europe/Riga":"Riga",
    "Europe/Sofia":"Sofija",
    "Europe/Tallinn":"Tallinn",
    "Europe/Vilnius":"Vilnius",
    "Europe/Athens":"Atena",
    "Europe/Istanbul":"Istanbul",
    "Europe/Minsk":"Minsk",
    "Asia/Jerusalem":"Jerusalem",
    "Africa/Harare":"Harare",
    "Africa/Johannesburg":"Johannesburg",
    "Europe/Volgograd":"Volgograd",
    "Europe/Moscow":"Moskva",
    "Asia/Kuwait":"Kuvajt",
    "Asia/Riyadh":"Riyadh",
    "Africa/Nairobi":"Nairobi",
    "Asia/Baghdad":"Baghdad",
    "Asia/Tehran":"Tehran",
    "Asia/Muscat":"Muscat",
    "Asia/Baku":"Baku",
    "Asia/Tbilisi":"Tbilisi",
    "Asia/Yerevan":"Yerevan",
    "Asia/Kabul":"Kabul",
    "Asia/Yekaterinburg":"Yekaterinburg",
    "Asia/Karachi":"Karachi",
    "Asia/Tashkent":"Taškent",
    "Asia/Calcutta":"Kolkata",
    "Asia/Kathmandu":"Kathmandu",
    "Asia/Dhaka":"Dhaka",
    "Asia/Colombo":"Colombo",
    "Asia/Almaty":"Almaty",
    "Asia/Novosibirsk":"Novosibirsk",
    "Asia/Rangoon":"Rangoon",
    "Asia/Bangkok":"Bangkok",
    "Asia/Jakarta":"Jakarta",
    "Asia/Krasnoyarsk":"Krasnojarsk",
    "Asia/Shanghai":"Šangaj",
    "Asia/Chongqing":"Chongqing",
    "Asia/Hong_Kong":"Hong Kong",
    "Asia/Urumqi":"Urumqi",
    "Asia/Kuala_Lumpur":"Kuala Lumpur",
    "Asia/Singapore":"Singapur",
    "Asia/Taipei":"Taipei",
    "Australia/Perth":"Perth",
    "Asia/Irkutsk":"Irkutsk",
    "Asia/Ulaanbaatar":"Ulaanbaatar",
    "Asia/Seoul":"Seoul",
    "Asia/Tokyo":"Tokio",
    "Asia/Yakutsk":"Yakutsk",
    "Australia/Darwin":"Darwin",
    "Australia/Adelaide":"Adelaide",
    "Australia/Melbourne":"Melbourne",
    "Australia/Sydney":"Sydney",
    "Australia/Brisbane":"Brisbane",
    "Australia/Hobart":"Hobart",
    "Asia/Vladivostok":"Vladivostok",
    "Pacific/Guam":"Guam",
    "Pacific/Port_Moresby":"Port Moresby",
    "Asia/Magadan":"Magadan",
    "Pacific/Noumea":"Noumea",
    "Pacific/Fiji":"Fiji",
    "Asia/Kamchatka":"Kamčatka",
    "Pacific/Majuro":"Majuro",
    "Pacific/Auckland":"Auckland",
    "Pacific/Tongatapu":"Tongatapu"
}