{
    "Pacific/Midway":"მიდუეი",
    "Pacific/Pago_Pago":"Pago Pago",
    "Pacific/Honolulu":"ჰონოლულუ",
    "America/Juneau":"ჯუნო",
    "America/Los_Angeles":"ლოს ანჯელესი",
    "America/Tijuana":"ტიხუანა",
    "America/Denver":"დენვერი",
    "America/Phoenix":"ფენიქსი",
    "America/Chihuahua":"ჩიჰუაჰუა",
    "America/Mazatlan":"მაზატლანი",
    "America/Chicago":"ჩიკაგო",
    "America/Regina":"რეჯინა",
    "America/Mexico_City":"მექსიკო სითი",
    "America/Monterrey":"მონტერეი",
    "America/Guatemala":"გუატემალა",
    "America/New_York":"ნიუ იორკი",
    "America/Indiana/Indianapolis":"Indianapolis, Indiana",
    "America/Bogota":"კოლუმბია",
    "America/Lima":"პერუ",
    "America/Halifax":"ჰალიფაქსი",
    "America/Caracas":"ვენესუელა",
    "America/La_Paz":"ბოლივია",
    "America/Santiago":"Santiago",
    "America/St_Johns":"St. John’s",
    "America/Sao_Paulo":"საო პაულო",
    "America/Argentina/Buenos_Aires":"Buenos Aires, Argentina",
    "America/Guyana":"Guyana",
    "America/Godthab":"Godthab",
    "Atlantic/South_Georgia":"South Georgia",
    "Atlantic/Azores":"აზორეს",
    "Atlantic/Cape_Verde":"Cape Verde",
    "Europe/Dublin":"Dublin",
    "Europe/London":"London",
    "Europe/Lisbon":"Lisbon",
    "Africa/Casablanca":"მაროკო",
    "Africa/Monrovia":"ლიბერია",
    "Etc/UTC":"UTC",
    "Europe/Belgrade":"Belgrade",
    "Europe/Bratislava":"Bratislava",
    "Europe/Budapest":"Budapest",
    "Europe/Ljubljana":"Ljubljana",
    "Europe/Prague":"Prague",
    "Europe/Sarajevo":"Sarajevo",
    "Europe/Skopje":"Skopje",
    "Europe/Warsaw":"Warsaw",
    "Europe/Zagreb":"Zagreb",
    "Europe/Brussels":"Brussels",
    "Europe/Copenhagen":"Copenhagen",
    "Europe/Madrid":"Madrid",
    "Europe/Paris":"Paris",
    "Europe/Amsterdam":"Amsterdam",
    "Europe/Berlin":"Berlin",
    "Europe/Rome":"Rome",
    "Europe/Stockholm":"Stockholm",
    "Europe/Vienna":"Vienna",
    "Africa/Algiers":"ალჟირი",
    "Europe/Bucharest":"Bucharest",
    "Africa/Cairo":"ეგვიპტე",
    "Europe/Helsinki":"Helsinki",
    "Europe/Kiev":"კიევი",
    "Europe/Riga":"Riga",
    "Europe/Sofia":"Sofia",
    "Europe/Tallinn":"Tallinn",
    "Europe/Vilnius":"Vilnius",
    "Europe/Athens":"Athens",
    "Europe/Istanbul":"Istanbul",
    "Europe/Minsk":"Minsk",
    "Asia/Jerusalem":"Jerusalem",
    "Africa/Harare":"ზიმბაბვე",
    "Africa/Johannesburg":"სამხრეთი აფრიკა",
    "Europe/Volgograd":"ვოლგოგრადი",
    "Europe/Moscow":"მოსკოვი",
    "Asia/Kuwait":"Kuwait",
    "Asia/Riyadh":"Riyadh",
    "Africa/Nairobi":"კენია",
    "Asia/Baghdad":"Baghdad",
    "Asia/Tehran":"Tehran",
    "Asia/Muscat":"Muscat",
    "Asia/Baku":"Baku",
    "Asia/Tbilisi":"Tbilisi",
    "Asia/Yerevan":"Yerevan",
    "Asia/Kabul":"Kabul",
    "Asia/Yekaterinburg":"ეკატერინბურგი",
    "Asia/Karachi":"Karachi",
    "Asia/Tashkent":"Tashkent",
    "Asia/Calcutta":"Kolkata",
    "Asia/Kathmandu":"Kathmandu",
    "Asia/Dhaka":"Dhaka",
    "Asia/Colombo":"Colombo",
    "Asia/Almaty":"ალმატი",
    "Asia/Novosibirsk":"ნოვოსიბირსკი",
    "Asia/Rangoon":"Rangoon",
    "Asia/Bangkok":"Bangkok",
    "Asia/Jakarta":"ჯაკარტა",
    "Asia/Krasnoyarsk":"კრასნოიარსკი",
    "Asia/Shanghai":"Shanghai",
    "Asia/Chongqing":"ჩონგქინგი",
    "Asia/Hong_Kong":"Hong Kong",
    "Asia/Urumqi":"ურუმქი",
    "Asia/Kuala_Lumpur":"Kuala Lumpur",
    "Asia/Singapore":"Singapore",
    "Asia/Taipei":"Taipei",
    "Australia/Perth":"პერთი",
    "Asia/Irkutsk":"ირკუტსკი",
    "Asia/Ulaanbaatar":"ულანბატარი",
    "Asia/Seoul":"Seoul",
    "Asia/Tokyo":"Tokyo",
    "Asia/Yakutsk":"იაკუტსკი",
    "Australia/Darwin":"დარვინი",
    "Australia/Adelaide":"ადელაიდა",
    "Australia/Melbourne":"მელბურნი",
    "Australia/Sydney":"სიდნეი",
    "Australia/Brisbane":"ბრისბეინი",
    "Australia/Hobart":"ჰობარტი",
    "Asia/Vladivostok":"ვლადივოსტოკი",
    "Pacific/Guam":"Guam",
    "Pacific/Port_Moresby":"Port Moresby",
    "Asia/Magadan":"მაგადანი",
    "Pacific/Noumea":"Noumea",
    "Pacific/Fiji":"Fiji",
    "Asia/Kamchatka":"კამჩატკა",
    "Pacific/Majuro":"მახურო",
    "Pacific/Auckland":"Auckland",
    "Pacific/Tongatapu":"Tongatapu"
}