{
    "Pacific/Midway":"ಮಿಡ್‌ವೇ",
    "Pacific/Pago_Pago":"ಪಾಗೊ ಪಾಗೊ",
    "Pacific/Honolulu":"ಹೊನಲುಲು",
    "America/Juneau":"ಜ್ಯುನಾವ್‌",
    "America/Los_Angeles":"ಲಾಸ್‌ ಏಂಜೆಲ್ಸ್‌‌",
    "America/Tijuana":"ತಿಜ್ವಾನಾ",
    "America/Denver":"ದೆನ್ವರ್‌",
    "America/Phoenix":"ಫೀನಿಕ್ಸ್‌‌",
    "America/Chihuahua":"ಚಿವಾವ",
    "America/Mazatlan":"ಮಜಾತ್ಲಾನ್‌‌",
    "America/Chicago":"ಶಿಕಾಗೋ",
    "America/Regina":"ರೆಜಿನಾ",
    "America/Mexico_City":"ಮೆಕ್ಸಿಕೋ ನಗರ",
    "America/Monterrey":"ಮಾಂತುರೇ",
    "America/Guatemala":"ಗ್ವಾಟೆಮಾಲಾ",
    "America/New_York":"ನ್ಯೂಯಾರ್ಕ್",
    "America/Indiana/Indianapolis":"Indianapolis, Indiana",
    "America/Bogota":"ಬೊಗೋಟ",
    "America/Lima":"ಲಿಮಾ",
    "America/Halifax":"ಹ್ಯಾಲಿಫ್ಯಾಕ್ಸ್‌‌",
    "America/Caracas":"ಕ್ಯಾರಕಾಸ್",
    "America/La_Paz":"ಲಾ ಪೆಜ್",
    "America/Santiago":"ಸ್ಯಾಂಟಿಯಾಗೊ",
    "America/St_Johns":"ಸೇಂಟ್‌‌.ಜಾನ್ಸ್‌‌‌",
    "America/Sao_Paulo":"ಸಾವ್ ಪಾಲೊ",
    "America/Argentina/Buenos_Aires":"Buenos Aires, Argentina",
    "America/Guyana":"ಗಯಾನಾ",
    "America/Godthab":"ಗೋಡ್ಥಾಬ್",
    "Atlantic/South_Georgia":"ದಕ್ಷಿಣ ಜಾರ್ಜಿಯಾ",
    "Atlantic/Azores":"ಅಝೋರಿಸ್",
    "Atlantic/Cape_Verde":"ಕೇಪ್ ವೆರ್ಡ್",
    "Europe/Dublin":"ಡುಬ್ಲಿನ್",
    "Europe/London":"ಲಂಡನ್",
    "Europe/Lisbon":"ಲಿಸ್ಬನ್",
    "Africa/Casablanca":"ಕಾಸಾಬ್ಲಾಂಕಾ",
    "Africa/Monrovia":"ಮೊನ್ರೋವಿಯಾ",
    "Etc/UTC":"UTC",
    "Europe/Belgrade":"ಬೆಲ್‌ಗ್ರಾದ್‌‌",
    "Europe/Bratislava":"ಬ್ರಾಟಿಸ್ಲಾವ",
    "Europe/Budapest":"ಬುಡಾಪೆಸ್ಟ್",
    "Europe/Ljubljana":"ಲ್ಯೂಬ್ಲ್ಯಾನಾ",
    "Europe/Prague":"ಪ್ರಾಗ್‌",
    "Europe/Sarajevo":"ಸರಜೆವೊ",
    "Europe/Skopje":"ಸ್ಕಾಪಿಯಾ",
    "Europe/Warsaw":"ವಾರ್ಸಾ",
    "Europe/Zagreb":"ಜಾಗ್ರೆಬ್‌‌",
    "Europe/Brussels":"ಬ್ರಸ್ಸೆಲ್ಸ್",
    "Europe/Copenhagen":"ಕೋಪೆನ್‌ಹೆಗನ್",
    "Europe/Madrid":"ಮ್ಯಾಡ್ರಿಡ್",
    "Europe/Paris":"ಪ್ಯಾರಿಸ್",
    "Europe/Amsterdam":"ಆಮ್‌ಸ್ಟರ್‌ಡ್ಯಾಮ್",
    "Europe/Berlin":"ಬರ್ಲಿನ್",
    "Europe/Rome":"ರೋಮ್",
    "Europe/Stockholm":"ಸ್ಟಾಕ್ಹೋಮ್",
    "Europe/Vienna":"ವಿಯೆನ್ನಾ",
    "Africa/Algiers":"ಅಲ್ಗೀರ್ಸ್",
    "Europe/Bucharest":"ಬುಕಾರೆಸ್ಟ್",
    "Africa/Cairo":"ಕೈರೋ",
    "Europe/Helsinki":"ಹೆಲ್ಸಿಂಕಿ",
    "Europe/Kiev":"ಕಿವ್",
    "Europe/Riga":"ರಿಗಾ",
    "Europe/Sofia":"ಸೋಫಿಯಾ",
    "Europe/Tallinn":"ಟ್ಯಾಲೆನ್‌‌",
    "Europe/Vilnius":"ವಿಲ್ನಿಯಸ್",
    "Europe/Athens":"ಅಥೆನ್ಸ್",
    "Europe/Istanbul":"ಇಸ್ತಾಂಬುಲ್‌‌",
    "Europe/Minsk":"ಮಿನ್‌ಸ್ಕ್",
    "Asia/Jerusalem":"ಜೆರುಸಲೆಮ್",
    "Africa/Harare":"ಹರಾರೆ",
    "Africa/Johannesburg":"ಜೊಹಾನ್ಸ್‌ಬರ್ಗ್",
    "Europe/Volgograd":"ವೊಲ್ಗೊಗ್ರಾದ್‌",
    "Europe/Moscow":"ಮಾಸ್ಕೋ",
    "Asia/Kuwait":"ಕುವೈತ್",
    "Asia/Riyadh":"ರಿಯಾದ್",
    "Africa/Nairobi":"ನೈರೋಬಿ",
    "Asia/Baghdad":"ಬಾಗ್ದಾದ್",
    "Asia/Tehran":"ತೆಹ್ರಾನ್",
    "Asia/Muscat":"ಮಸ್ಕತ್",
    "Asia/Baku":"ಬಕು",
    "Asia/Tbilisi":"ತ್ಯುಬಿಲ್ಸಿ",
    "Asia/Yerevan":"ಯೆರಿವಾನ್",
    "Asia/Kabul":"ಕಾಬೂಲ್",
    "Asia/Yekaterinburg":"ಯಿಕಟೆರೆನ್‌ಬರ್ಗ್‌",
    "Asia/Karachi":"ಕರಾಚಿ",
    "Asia/Tashkent":"ತಾಶ್ಕೆಂಟ್",
    "Asia/Calcutta":"ಕೊಲ್ಕತ್ತಾ",
    "Asia/Kathmandu":"Kathmandu",
    "Asia/Dhaka":"ಢಾಕಾ",
    "Asia/Colombo":"ಕೊಲಂಬೊ",
    "Asia/Almaty":"ಅಲ್ಮಾಟಿ",
    "Asia/Novosibirsk":"ನವೊಸ್‌ಬಿಸರ್ಕ್‌",
    "Asia/Rangoon":"ರಂಗೂನ್",
    "Asia/Bangkok":"ಬ್ಯಾಂಕಾಕ್",
    "Asia/Jakarta":"ಜಕಾರ್ತಾ",
    "Asia/Krasnoyarsk":"ಕ್ರಾಸ್ನಿಯಾರ್ಸ್ಕ್‌",
    "Asia/Shanghai":"ಶಾಂಗೈ",
    "Asia/Chongqing":"ಚೋಂಗ್‌ಕಿಂಗ್‌",
    "Asia/Hong_Kong":"ಹಾಂಗ್ ಕಾಂಗ್",
    "Asia/Urumqi":"ಯೂರ‍್ಯೂಮ್‌ಚೀ",
    "Asia/Kuala_Lumpur":"ಕೌಲಾ ಲಂಪುರ",
    "Asia/Singapore":"ಸಿಂಗಾಪೂರ್",
    "Asia/Taipei":"ತೈಪೆ",
    "Australia/Perth":"ಪರ್ಥ್‌",
    "Asia/Irkutsk":"ಇರ್ಕುತ್ಸಕ್‌",
    "Asia/Ulaanbaatar":"ಉಲಾನ್ಬಾತರ್",
    "Asia/Seoul":"ಸಿಯೋಲ್",
    "Asia/Tokyo":"ಟೋಕಿಯೊ",
    "Asia/Yakutsk":"ಯಕುತ್ಸಕ್‌",
    "Australia/Darwin":"ಡಾರ್ವಿನ್‌",
    "Australia/Adelaide":"ಅಡಿಲೇಡ್‌",
    "Australia/Melbourne":"ಮೆಲ್ಬೋರ್ನ್‌",
    "Australia/Sydney":"ಸಿಡ್ನಿ",
    "Australia/Brisbane":"ಬ್ರಿಸ್ಬೇನ್‌",
    "Australia/Hobart":"ಹೋಬರ್ಟ್‌",
    "Asia/Vladivostok":"ವ್ಲ್ಯಾದಿವೊಸ್ತೊಕ್‌",
    "Pacific/Guam":"ಗ್ವಾಮ್",
    "Pacific/Port_Moresby":"ಪೋರ್ಟ್ ಮೋರ್ಸ್‌ಬೆ",
    "Asia/Magadan":"ಮಘದಾನ್‌",
    "Pacific/Noumea":"ನ್ಯೂಮಿಯಾ",
    "Pacific/Fiji":"ಫಿಜಿ",
    "Asia/Kamchatka":"ಕಮ್ಚತ್ಕ",
    "Pacific/Majuro":"ಮಜುರೊ",
    "Pacific/Auckland":"ಆಕ್ ಲ್ಯಾಂಡ್",
    "Pacific/Tongatapu":"ಟೊಂಗಾಟಾಪು"
}