{
    "Pacific/Midway":"Мидвеј",
    "Pacific/Pago_Pago":"Pago Pago",
    "Pacific/Honolulu":"Хонолулу",
    "America/Juneau":"Џуно",
    "America/Los_Angeles":"Лос Анџелес",
    "America/Tijuana":"Тихуана",
    "America/Denver":"Денвер",
    "America/Phoenix":"Феникс",
    "America/Chihuahua":"Чихуахуа",
    "America/Mazatlan":"Мецатлан",
    "America/Chicago":"Чикаго",
    "America/Regina":"Реџина",
    "America/Mexico_City":"Мексико Сити",
    "America/Monterrey":"Монтереј",
    "America/Guatemala":"Guatemala",
    "America/New_York":"Њујорк",
    "America/Indiana/Indianapolis":"Indianapolis, Indiana",
    "America/Bogota":"Bogota",
    "America/Lima":"Lima",
    "America/Halifax":"Халифакс",
    "America/Caracas":"Caracas",
    "America/La_Paz":"La Paz",
    "America/Santiago":"Santiago",
    "America/St_Johns":"Сент Џонс",
    "America/Sao_Paulo":"Сао Паоло",
    "America/Argentina/Buenos_Aires":"Buenos Aires, Argentina",
    "America/Guyana":"Guyana",
    "America/Godthab":"Godthab",
    "Atlantic/South_Georgia":"South Georgia",
    "Atlantic/Azores":"Азори",
    "Atlantic/Cape_Verde":"Cape Verde",
    "Europe/Dublin":"Dublin",
    "Europe/London":"London",
    "Europe/Lisbon":"Lisbon",
    "Africa/Casablanca":"Casablanca",
    "Africa/Monrovia":"Monrovia",
    "Etc/UTC":"UTC",
    "Europe/Belgrade":"Belgrade",
    "Europe/Bratislava":"Bratislava",
    "Europe/Budapest":"Budapest",
    "Europe/Ljubljana":"Ljubljana",
    "Europe/Prague":"Prague",
    "Europe/Sarajevo":"Sarajevo",
    "Europe/Skopje":"Skopje",
    "Europe/Warsaw":"Warsaw",
    "Europe/Zagreb":"Zagreb",
    "Europe/Brussels":"Brussels",
    "Europe/Copenhagen":"Copenhagen",
    "Europe/Madrid":"Madrid",
    "Europe/Paris":"Paris",
    "Europe/Amsterdam":"Amsterdam",
    "Europe/Berlin":"Berlin",
    "Europe/Rome":"Rome",
    "Europe/Stockholm":"Stockholm",
    "Europe/Vienna":"Vienna",
    "Africa/Algiers":"Algiers",
    "Europe/Bucharest":"Bucharest",
    "Africa/Cairo":"Cairo",
    "Europe/Helsinki":"Helsinki",
    "Europe/Kiev":"Kiev",
    "Europe/Riga":"Riga",
    "Europe/Sofia":"Sofia",
    "Europe/Tallinn":"Tallinn",
    "Europe/Vilnius":"Vilnius",
    "Europe/Athens":"Athens",
    "Europe/Istanbul":"Istanbul",
    "Europe/Minsk":"Minsk",
    "Asia/Jerusalem":"Jerusalem",
    "Africa/Harare":"Harare",
    "Africa/Johannesburg":"Johannesburg",
    "Europe/Volgograd":"Волгоград",
    "Europe/Moscow":"Москва",
    "Asia/Kuwait":"Kuwait",
    "Asia/Riyadh":"Riyadh",
    "Africa/Nairobi":"Nairobi",
    "Asia/Baghdad":"Baghdad",
    "Asia/Tehran":"Tehran",
    "Asia/Muscat":"Muscat",
    "Asia/Baku":"Baku",
    "Asia/Tbilisi":"Tbilisi",
    "Asia/Yerevan":"Yerevan",
    "Asia/Kabul":"Kabul",
    "Asia/Yekaterinburg":"Јекатеринбург",
    "Asia/Karachi":"Karachi",
    "Asia/Tashkent":"Tashkent",
    "Asia/Calcutta":"Kolkata",
    "Asia/Kathmandu":"Kathmandu",
    "Asia/Dhaka":"Dhaka",
    "Asia/Colombo":"Colombo",
    "Asia/Almaty":"Алма-Ата",
    "Asia/Novosibirsk":"Новосибирск",
    "Asia/Rangoon":"Rangoon",
    "Asia/Bangkok":"Bangkok",
    "Asia/Jakarta":"Џакарта",
    "Asia/Krasnoyarsk":"Краснојарск",
    "Asia/Shanghai":"Shanghai",
    "Asia/Chongqing":"Чонгкинг",
    "Asia/Hong_Kong":"Hong Kong",
    "Asia/Urumqi":"Урумки",
    "Asia/Kuala_Lumpur":"Kuala Lumpur",
    "Asia/Singapore":"Singapore",
    "Asia/Taipei":"Taipei",
    "Australia/Perth":"Перт",
    "Asia/Irkutsk":"Иркутск",
    "Asia/Ulaanbaatar":"Улан Батор",
    "Asia/Seoul":"Seoul",
    "Asia/Tokyo":"Tokyo",
    "Asia/Yakutsk":"Јакутск",
    "Australia/Darwin":"Дарвин",
    "Australia/Adelaide":"Аделаида",
    "Australia/Melbourne":"Мелбурн",
    "Australia/Sydney":"Сиднеј",
    "Australia/Brisbane":"Бризбејн",
    "Australia/Hobart":"Хобарт",
    "Asia/Vladivostok":"Владивосток",
    "Pacific/Guam":"Guam",
    "Pacific/Port_Moresby":"Port Moresby",
    "Asia/Magadan":"Магадан",
    "Pacific/Noumea":"Noumea",
    "Pacific/Fiji":"Fiji",
    "Asia/Kamchatka":"Камчатка",
    "Pacific/Majuro":"Majuro",
    "Pacific/Auckland":"Auckland",
    "Pacific/Tongatapu":"Tongatapu"
}