{
    "Pacific/Midway":"मिडवे",
    "Pacific/Pago_Pago":"Pago Pago",
    "Pacific/Honolulu":"होनोलुलु",
    "America/Juneau":"जुनिउ",
    "America/Los_Angeles":"लस् एन्जेलस",
    "America/Tijuana":"तिजुआना",
    "America/Denver":"डेन्भर",
    "America/Phoenix":"फोनिक्स",
    "America/Chihuahua":"चिहुआहुआ",
    "America/Mazatlan":"माजाट्लान",
    "America/Chicago":"चिकागो",
    "America/Regina":"रेजिना",
    "America/Mexico_City":"मेक्सिको सिटी",
    "America/Monterrey":"मोन्टेर्रे",
    "America/Guatemala":"Guatemala",
    "America/New_York":"न्युयोर्क",
    "America/Indiana/Indianapolis":"Indianapolis, Indiana",
    "America/Bogota":"Bogota",
    "America/Lima":"Lima",
    "America/Halifax":"हालेफाक्स",
    "America/Caracas":"Caracas",
    "America/La_Paz":"La Paz",
    "America/Santiago":"Santiago",
    "America/St_Johns":"सेन्ट जोन्स",
    "America/Sao_Paulo":"साओ पाउलो",
    "America/Argentina/Buenos_Aires":"Buenos Aires, Argentina",
    "America/Guyana":"Guyana",
    "America/Godthab":"Godthab",
    "Atlantic/South_Georgia":"South Georgia",
    "Atlantic/Azores":"आजोर्स",
    "Atlantic/Cape_Verde":"Cape Verde",
    "Europe/Dublin":"Dublin",
    "Europe/London":"London",
    "Europe/Lisbon":"Lisbon",
    "Africa/Casablanca":"Casablanca",
    "Africa/Monrovia":"Monrovia",
    "Etc/UTC":"UTC",
    "Europe/Belgrade":"Belgrade",
    "Europe/Bratislava":"Bratislava",
    "Europe/Budapest":"Budapest",
    "Europe/Ljubljana":"Ljubljana",
    "Europe/Prague":"Prague",
    "Europe/Sarajevo":"Sarajevo",
    "Europe/Skopje":"Skopje",
    "Europe/Warsaw":"Warsaw",
    "Europe/Zagreb":"Zagreb",
    "Europe/Brussels":"Brussels",
    "Europe/Copenhagen":"Copenhagen",
    "Europe/Madrid":"Madrid",
    "Europe/Paris":"Paris",
    "Europe/Amsterdam":"Amsterdam",
    "Europe/Berlin":"Berlin",
    "Europe/Rome":"Rome",
    "Europe/Stockholm":"Stockholm",
    "Europe/Vienna":"Vienna",
    "Africa/Algiers":"Algiers",
    "Europe/Bucharest":"Bucharest",
    "Africa/Cairo":"Cairo",
    "Europe/Helsinki":"Helsinki",
    "Europe/Kiev":"किभ",
    "Europe/Riga":"Riga",
    "Europe/Sofia":"Sofia",
    "Europe/Tallinn":"Tallinn",
    "Europe/Vilnius":"Vilnius",
    "Europe/Athens":"Athens",
    "Europe/Istanbul":"Istanbul",
    "Europe/Minsk":"Minsk",
    "Asia/Jerusalem":"Jerusalem",
    "Africa/Harare":"Harare",
    "Africa/Johannesburg":"Johannesburg",
    "Europe/Volgograd":"भोल्गोग्राद",
    "Europe/Moscow":"मस्को",
    "Asia/Kuwait":"Kuwait",
    "Asia/Riyadh":"Riyadh",
    "Africa/Nairobi":"Nairobi",
    "Asia/Baghdad":"Baghdad",
    "Asia/Tehran":"Tehran",
    "Asia/Muscat":"Muscat",
    "Asia/Baku":"Baku",
    "Asia/Tbilisi":"Tbilisi",
    "Asia/Yerevan":"Yerevan",
    "Asia/Kabul":"Kabul",
    "Asia/Yekaterinburg":"एकटरिनबुर्ग",
    "Asia/Karachi":"Karachi",
    "Asia/Tashkent":"Tashkent",
    "Asia/Calcutta":"Kolkata",
    "Asia/Kathmandu":"Kathmandu",
    "Asia/Dhaka":"Dhaka",
    "Asia/Colombo":"Colombo",
    "Asia/Almaty":"आल्माटी",
    "Asia/Novosibirsk":"नोबोसिबिर्स्क",
    "Asia/Rangoon":"Rangoon",
    "Asia/Bangkok":"Bangkok",
    "Asia/Jakarta":"जाकार्ता",
    "Asia/Krasnoyarsk":"क्रास्नोयार्स्क",
    "Asia/Shanghai":"Shanghai",
    "Asia/Chongqing":"चोङकिङ",
    "Asia/Hong_Kong":"Hong Kong",
    "Asia/Urumqi":"उरूम्की",
    "Asia/Kuala_Lumpur":"Kuala Lumpur",
    "Asia/Singapore":"Singapore",
    "Asia/Taipei":"Taipei",
    "Australia/Perth":"पर्थ",
    "Asia/Irkutsk":"इर्कुत्स्क",
    "Asia/Ulaanbaatar":"उलानबटार",
    "Asia/Seoul":"Seoul",
    "Asia/Tokyo":"Tokyo",
    "Asia/Yakutsk":"याकुत्स्क",
    "Australia/Darwin":"डार्विन",
    "Australia/Adelaide":"एडेलेड",
    "Australia/Melbourne":"मेल्बर्न",
    "Australia/Sydney":"सिड्नी",
    "Australia/Brisbane":"ब्रिस्बेन",
    "Australia/Hobart":"होभार्ट",
    "Asia/Vladivostok":"भ्लाडिभास्टोक",
    "Pacific/Guam":"Guam",
    "Pacific/Port_Moresby":"Port Moresby",
    "Asia/Magadan":"मागाडान",
    "Pacific/Noumea":"Noumea",
    "Pacific/Fiji":"Fiji",
    "Asia/Kamchatka":"कामचट्का",
    "Pacific/Majuro":"माजुरो",
    "Pacific/Auckland":"Auckland",
    "Pacific/Tongatapu":"Tongatapu"
}