{
    "Pacific/Midway":"Midway",
    "Pacific/Pago_Pago":"Pago Pago",
    "Pacific/Honolulu":"Honolulu",
    "America/Juneau":"Juneau",
    "America/Los_Angeles":"Los Angeles",
    "America/Tijuana":"Tijuana",
    "America/Denver":"Denver",
    "America/Phoenix":"Phoenix",
    "America/Chihuahua":"Chihuahua",
    "America/Mazatlan":"Mazatlan",
    "America/Chicago":"Chicago",
    "America/Regina":"Regina",
    "America/Mexico_City":"Meksyk",
    "America/Monterrey":"Monterrey",
    "America/Guatemala":"Gwatemala",
    "America/New_York":"Nowy Jork",
    "America/Indiana/Indianapolis":"Indianapolis, Indiana",
    "America/Bogota":"Bogota",
    "America/Lima":"Lima",
    "America/Halifax":"Halifax",
    "America/Caracas":"Caracas",
    "America/La_Paz":"La Paz",
    "America/Santiago":"Santiago",
    "America/St_Johns":"St. John’s",
    "America/Sao_Paulo":"Sao Paulo",
    "America/Argentina/Buenos_Aires":"Buenos Aires, Argentina",
    "America/Guyana":"Gujana",
    "America/Godthab":"Nuuk",
    "Atlantic/South_Georgia":"Georgia Południowa",
    "Atlantic/Azores":"Azory",
    "Atlantic/Cape_Verde":"Zielony Przylądek",
    "Europe/Dublin":"Dublin",
    "Europe/London":"Londyn",
    "Europe/Lisbon":"Lizbona",
    "Africa/Casablanca":"Casablanca",
    "Africa/Monrovia":"Monrovia",
    "Etc/UTC":"UTC",
    "Europe/Belgrade":"Belgrad",
    "Europe/Bratislava":"Bratysława",
    "Europe/Budapest":"Budapeszt",
    "Europe/Ljubljana":"Lublana",
    "Europe/Prague":"Praga",
    "Europe/Sarajevo":"Sarajewo",
    "Europe/Skopje":"Skopje",
    "Europe/Warsaw":"Warszawa",
    "Europe/Zagreb":"Zagrzeb",
    "Europe/Brussels":"Bruksela",
    "Europe/Copenhagen":"Kopenhaga",
    "Europe/Madrid":"Madryt",
    "Europe/Paris":"Paryż",
    "Europe/Amsterdam":"Amsterdam",
    "Europe/Berlin":"Berlin",
    "Europe/Rome":"Rzym",
    "Europe/Stockholm":"Sztokholm",
    "Europe/Vienna":"Wiedeń",
    "Africa/Algiers":"Algier",
    "Europe/Bucharest":"Bukareszt",
    "Africa/Cairo":"Kair",
    "Europe/Helsinki":"Helsinki",
    "Europe/Kiev":"Kijów",
    "Europe/Riga":"Ryga",
    "Europe/Sofia":"Sofia",
    "Europe/Tallinn":"Tallin",
    "Europe/Vilnius":"Wilno",
    "Europe/Athens":"Ateny",
    "Europe/Istanbul":"Stambuł",
    "Europe/Minsk":"Mińsk",
    "Asia/Jerusalem":"Jerozolima",
    "Africa/Harare":"Harare",
    "Africa/Johannesburg":"Johannesburg",
    "Europe/Volgograd":"Wołgograd",
    "Europe/Moscow":"Moskwa",
    "Asia/Kuwait":"Kuwejt",
    "Asia/Riyadh":"Rijad",
    "Africa/Nairobi":"Nairobi",
    "Asia/Baghdad":"Bagdad",
    "Asia/Tehran":"Teheran",
    "Asia/Muscat":"Maskat",
    "Asia/Baku":"Baku",
    "Asia/Tbilisi":"Tbilisi",
    "Asia/Yerevan":"Erewan",
    "Asia/Kabul":"Kabul",
    "Asia/Yekaterinburg":"Jekaterynburg",
    "Asia/Karachi":"Karaczi",
    "Asia/Tashkent":"Taszkient",
    "Asia/Calcutta":"Kalkuta",
    "Asia/Kathmandu":"Kathmandu",
    "Asia/Dhaka":"Dakka",
    "Asia/Colombo":"Kolombo",
    "Asia/Almaty":"Ałma Ata",
    "Asia/Novosibirsk":"Nowosybirsk",
    "Asia/Rangoon":"Rangun",
    "Asia/Bangkok":"Bangkok",
    "Asia/Jakarta":"Dżakarta",
    "Asia/Krasnoyarsk":"Krasnojarsk",
    "Asia/Shanghai":"Szanghaj",
    "Asia/Chongqing":"Czunking",
    "Asia/Hong_Kong":"Hongkong",
    "Asia/Urumqi":"Urumczi",
    "Asia/Kuala_Lumpur":"Kuala Lumpur",
    "Asia/Singapore":"Singapur",
    "Asia/Taipei":"Tajpej",
    "Australia/Perth":"Perth",
    "Asia/Irkutsk":"Irkuck",
    "Asia/Ulaanbaatar":"Ułan Bator",
    "Asia/Seoul":"Seul",
    "Asia/Tokyo":"Tokio",
    "Asia/Yakutsk":"Jakuck",
    "Australia/Darwin":"Darwin",
    "Australia/Adelaide":"Adelajda",
    "Australia/Melbourne":"Melbourne",
    "Australia/Sydney":"Sydney",
    "Australia/Brisbane":"Brisbane",
    "Australia/Hobart":"Hobart",
    "Asia/Vladivostok":"Władywostok",
    "Pacific/Guam":"Guam",
    "Pacific/Port_Moresby":"Port Moresby",
    "Asia/Magadan":"Magadan",
    "Pacific/Noumea":"Numea",
    "Pacific/Fiji":"Fidżi",
    "Asia/Kamchatka":"Kamczatka",
    "Pacific/Majuro":"Majuro",
    "Pacific/Auckland":"Auckland",
    "Pacific/Tongatapu":"Tongatapu"
}