{
    "Pacific/Midway":"Midway",
    "Pacific/Pago_Pago":"Pago Pago",
    "Pacific/Honolulu":"Honolulu",
    "America/Juneau":"Juneau",
    "America/Los_Angeles":"Los Angeles",
    "America/Tijuana":"Tijuana",
    "America/Denver":"Denver",
    "America/Phoenix":"Phoenix",
    "America/Chihuahua":"Chihuahua",
    "America/Mazatlan":"Mazatlan",
    "America/Chicago":"Chicago",
    "America/Regina":"Regina",
    "America/Mexico_City":"Cidade do México",
    "America/Monterrey":"Monterrey",
    "America/Guatemala":"Guatemala",
    "America/New_York":"Nova York",
    "America/Indiana/Indianapolis":"Indianapolis, Indiana",
    "America/Bogota":"Bogotá",
    "America/Lima":"Lima",
    "America/Halifax":"Halifax",
    "America/Caracas":"Caracas",
    "America/La_Paz":"La Paz",
    "America/Santiago":"Santiago",
    "America/St_Johns":"St. John's",
    "America/Sao_Paulo":"São Paulo",
    "America/Argentina/Buenos_Aires":"Buenos Aires, Argentina",
    "America/Guyana":"Guiana",
    "America/Godthab":"Godthab",
    "Atlantic/South_Georgia":"Geórgia do Sul",
    "Atlantic/Azores":"Açores",
    "Atlantic/Cape_Verde":"Cabo Verde",
    "Europe/Dublin":"Dublin",
    "Europe/London":"Londres",
    "Europe/Lisbon":"Lisboa",
    "Africa/Casablanca":"Casablanca",
    "Africa/Monrovia":"Monróvia",
    "Etc/UTC":"UTC",
    "Europe/Belgrade":"Belgrade",
    "Europe/Bratislava":"Bratislava",
    "Europe/Budapest":"Budapeste",
    "Europe/Ljubljana":"Liubliana",
    "Europe/Prague":"Praga",
    "Europe/Sarajevo":"Sarajevo",
    "Europe/Skopje":"Skopje",
    "Europe/Warsaw":"Varsóvia",
    "Europe/Zagreb":"Zagreb",
    "Europe/Brussels":"Bruxelas",
    "Europe/Copenhagen":"Copenhaga",
    "Europe/Madrid":"Madrid",
    "Europe/Paris":"Paris",
    "Europe/Amsterdam":"Amesterdão",
    "Europe/Berlin":"Berlim",
    "Europe/Rome":"Roma",
    "Europe/Stockholm":"Estocolmo",
    "Europe/Vienna":"Viena",
    "Africa/Algiers":"Argel",
    "Europe/Bucharest":"Bucareste",
    "Africa/Cairo":"Cairo",
    "Europe/Helsinki":"Helsínquia",
    "Europe/Kiev":"Kiev",
    "Europe/Riga":"Riga",
    "Europe/Sofia":"Sófia",
    "Europe/Tallinn":"Tallinn",
    "Europe/Vilnius":"Vilnius",
    "Europe/Athens":"Atenas",
    "Europe/Istanbul":"Istambul",
    "Europe/Minsk":"Minsk",
    "Asia/Jerusalem":"Jerusalém",
    "Africa/Harare":"Harare",
    "Africa/Johannesburg":"Joanesburgo",
    "Europe/Volgograd":"Volgogrado",
    "Europe/Moscow":"Moscovo",
    "Asia/Kuwait":"Kuwait",
    "Asia/Riyadh":"Riade",
    "Africa/Nairobi":"Nairobi",
    "Asia/Baghdad":"Bagdade",
    "Asia/Tehran":"Teerão",
    "Asia/Muscat":"Muscat",
    "Asia/Baku":"Baku",
    "Asia/Tbilisi":"Tbilisi",
    "Asia/Yerevan":"Erevan",
    "Asia/Kabul":"Kabul",
    "Asia/Yekaterinburg":"Ecaterimburgo",
    "Asia/Karachi":"Karachi",
    "Asia/Tashkent":"Tashkent",
    "Asia/Calcutta":"Kolkata",
    "Asia/Kathmandu":"Kathmandu",
    "Asia/Dhaka":"Daca",
    "Asia/Colombo":"Colombo",
    "Asia/Almaty":"Almaty",
    "Asia/Novosibirsk":"Novosibirsk",
    "Asia/Rangoon":"Rangoon",
    "Asia/Bangkok":"Bangkok",
    "Asia/Jakarta":"Jacarta",
    "Asia/Krasnoyarsk":"Krasnoyarsk",
    "Asia/Shanghai":"Xangai",
    "Asia/Chongqing":"Chongqing",
    "Asia/Hong_Kong":"Hong Kong",
    "Asia/Urumqi":"Urumqi",
    "Asia/Kuala_Lumpur":"Kuala Lumpur",
    "Asia/Singapore":"Cingapura",
    "Asia/Taipei":"Taipei",
    "Australia/Perth":"Perth",
    "Asia/Irkutsk":"Irkutsk",
    "Asia/Ulaanbaatar":"Ulan Bator",
    "Asia/Seoul":"Seul",
    "Asia/Tokyo":"Tóquio",
    "Asia/Yakutsk":"Yakutsk",
    "Australia/Darwin":"Darwin",
    "Australia/Adelaide":"Adelaide",
    "Australia/Melbourne":"Melbourne",
    "Australia/Sydney":"Sydney",
    "Australia/Brisbane":"Brisbane",
    "Australia/Hobart":"Hobart",
    "Asia/Vladivostok":"Vladivostok",
    "Pacific/Guam":"Guam",
    "Pacific/Port_Moresby":"Port Moresby",
    "Asia/Magadan":"Magadan",
    "Pacific/Noumea":"Noumea",
    "Pacific/Fiji":"Fiji",
    "Asia/Kamchatka":"Kamchatka",
    "Pacific/Majuro":"Majuro",
    "Pacific/Auckland":"Auckland",
    "Pacific/Tongatapu":"Tongatapu"
}