{
    "Pacific/Midway":"Atolul Midway",
    "Pacific/Pago_Pago":"Pago Pago",
    "Pacific/Honolulu":"Honolulu",
    "America/Juneau":"Juneau",
    "America/Los_Angeles":"Los Angeles",
    "America/Tijuana":"Tijuana",
    "America/Denver":"Denver",
    "America/Phoenix":"Phoenix",
    "America/Chihuahua":"Chihuahua",
    "America/Mazatlan":"Mazatlan",
    "America/Chicago":"Chicago",
    "America/Regina":"Regina",
    "America/Mexico_City":"Mexico",
    "America/Monterrey":"Monterrey",
    "America/Guatemala":"Guatemala",
    "America/New_York":"New York",
    "America/Indiana/Indianapolis":"Indianapolis, Indiana",
    "America/Bogota":"Bogota",
    "America/Lima":"Lima",
    "America/Halifax":"Halifax",
    "America/Caracas":"Caracas",
    "America/La_Paz":"La Paz",
    "America/Santiago":"Santiago",
    "America/St_Johns":"St. John’s",
    "America/Sao_Paulo":"Sao Paulo",
    "America/Argentina/Buenos_Aires":"Buenos Aires, Argentina",
    "America/Guyana":"Guyana",
    "America/Godthab":"Godthab",
    "Atlantic/South_Georgia":"Georgia de Sud",
    "Atlantic/Azores":"Azore",
    "Atlantic/Cape_Verde":"Capul Verde",
    "Europe/Dublin":"Dublin",
    "Europe/London":"Londra",
    "Europe/Lisbon":"Lisabona",
    "Africa/Casablanca":"Casablanca",
    "Africa/Monrovia":"Monrovia",
    "Etc/UTC":"UTC",
    "Europe/Belgrade":"Belgrad",
    "Europe/Bratislava":"Bratislava",
    "Europe/Budapest":"Budapesta",
    "Europe/Ljubljana":"Ljubljana",
    "Europe/Prague":"Praga",
    "Europe/Sarajevo":"Sarajevo",
    "Europe/Skopje":"Skopje",
    "Europe/Warsaw":"Varșovia",
    "Europe/Zagreb":"Zagreb",
    "Europe/Brussels":"Bruxelles",
    "Europe/Copenhagen":"Copenhaga",
    "Europe/Madrid":"Madrid",
    "Europe/Paris":"Paris",
    "Europe/Amsterdam":"Amsterdam",
    "Europe/Berlin":"Berlin",
    "Europe/Rome":"Roma",
    "Europe/Stockholm":"Stockholm",
    "Europe/Vienna":"Viena",
    "Africa/Algiers":"Alger",
    "Europe/Bucharest":"București",
    "Africa/Cairo":"Cairo",
    "Europe/Helsinki":"Helsinki",
    "Europe/Kiev":"Kiev",
    "Europe/Riga":"Riga",
    "Europe/Sofia":"Sofia",
    "Europe/Tallinn":"Tallinn",
    "Europe/Vilnius":"Vilnius",
    "Europe/Athens":"Atena",
    "Europe/Istanbul":"Istanbul",
    "Europe/Minsk":"Minsk",
    "Asia/Jerusalem":"Ierusalim",
    "Africa/Harare":"Harare",
    "Africa/Johannesburg":"Johannesburg",
    "Europe/Volgograd":"Volgograd",
    "Europe/Moscow":"Moscova",
    "Asia/Kuwait":"Kuweit",
    "Asia/Riyadh":"Riyad",
    "Africa/Nairobi":"Nairobi",
    "Asia/Baghdad":"Bagdad",
    "Asia/Tehran":"Teheran",
    "Asia/Muscat":"Muscat",
    "Asia/Baku":"Baku",
    "Asia/Tbilisi":"Tbilisi",
    "Asia/Yerevan":"Erevan",
    "Asia/Kabul":"Kabul",
    "Asia/Yekaterinburg":"Ekaterinburg",
    "Asia/Karachi":"Karachi",
    "Asia/Tashkent":"Tashkent",
    "Asia/Calcutta":"Calcutta",
    "Asia/Kathmandu":"Kathmandu",
    "Asia/Dhaka":"Dacca",
    "Asia/Colombo":"Colombo",
    "Asia/Almaty":"Almaty",
    "Asia/Novosibirsk":"Novosibirsk",
    "Asia/Rangoon":"Yangon",
    "Asia/Bangkok":"Bangkok",
    "Asia/Jakarta":"Jakarta",
    "Asia/Krasnoyarsk":"Krasnoiarsk",
    "Asia/Shanghai":"Shanghai",
    "Asia/Chongqing":"Chongqing",
    "Asia/Hong_Kong":"Hong Kong",
    "Asia/Urumqi":"Urumqi",
    "Asia/Kuala_Lumpur":"Kuala Lumpur",
    "Asia/Singapore":"Singapore",
    "Asia/Taipei":"Taipei",
    "Australia/Perth":"Perth",
    "Asia/Irkutsk":"Irkuțk",
    "Asia/Ulaanbaatar":"Ulan Bator",
    "Asia/Seoul":"Seul",
    "Asia/Tokyo":"Tokio",
    "Asia/Yakutsk":"Yakuțk",
    "Australia/Darwin":"Darwin",
    "Australia/Adelaide":"Adelaide",
    "Australia/Melbourne":"Melbourne",
    "Australia/Sydney":"Sydney",
    "Australia/Brisbane":"Brisbane",
    "Australia/Hobart":"Hobart",
    "Asia/Vladivostok":"Vladivostok",
    "Pacific/Guam":"Insula Guam",
    "Pacific/Port_Moresby":"Port Moresby",
    "Asia/Magadan":"Magadan",
    "Pacific/Noumea":"Noumea",
    "Pacific/Fiji":"Fiji",
    "Asia/Kamchatka":"Kamciatka",
    "Pacific/Majuro":"Majuro",
    "Pacific/Auckland":"Auckland",
    "Pacific/Tongatapu":"Tongatapu"
}