{
    "Pacific/Midway":"Midway",
    "Pacific/Pago_Pago":"Pago Pago",
    "Pacific/Honolulu":"Honolulu",
    "America/Juneau":"Juneau",
    "America/Los_Angeles":"Los Angeles",
    "America/Tijuana":"Tijuana",
    "America/Denver":"Denver",
    "America/Phoenix":"Phoenix",
    "America/Chihuahua":"Chihuahua",
    "America/Mazatlan":"Mazatlán",
    "America/Chicago":"Chicago",
    "America/Regina":"Régina",
    "America/Mexico_City":"Mexico City",
    "America/Monterrey":"Monterrey",
    "America/Guatemala":"Guatemala",
    "America/New_York":"New York",
    "America/Indiana/Indianapolis":"Indianapolis, Indiana",
    "America/Bogota":"Bogotá",
    "America/Lima":"Lima",
    "America/Halifax":"Halifax",
    "America/Caracas":"Caracas",
    "America/La_Paz":"La Paz",
    "America/Santiago":"Santiago",
    "America/St_Johns":"St. Johns",
    "America/Sao_Paulo":"São Paulo",
    "America/Argentina/Buenos_Aires":"Buenos Aires, Argentina",
    "America/Guyana":"Guyana",
    "America/Godthab":"Godthåb",
    "Atlantic/South_Georgia":"Grytviken",
    "Atlantic/Azores":"Azorerna",
    "Atlantic/Cape_Verde":"Kap Verde",
    "Europe/Dublin":"Dublin",
    "Europe/London":"London",
    "Europe/Lisbon":"Lissabon",
    "Africa/Casablanca":"Casablanca",
    "Africa/Monrovia":"Monrovia",
    "Etc/UTC":"UTC",
    "Europe/Belgrade":"Belgrad",
    "Europe/Bratislava":"Bratislava",
    "Europe/Budapest":"Budapest",
    "Europe/Ljubljana":"Ljubliana",
    "Europe/Prague":"Prag",
    "Europe/Sarajevo":"Sarajevo",
    "Europe/Skopje":"Skopje",
    "Europe/Warsaw":"Warszawa",
    "Europe/Zagreb":"Zagreb",
    "Europe/Brussels":"Bryssel",
    "Europe/Copenhagen":"Köpenhamn",
    "Europe/Madrid":"Madrid",
    "Europe/Paris":"Paris",
    "Europe/Amsterdam":"Amsterdam",
    "Europe/Berlin":"Berlin",
    "Europe/Rome":"Rom",
    "Europe/Stockholm":"Stockholm",
    "Europe/Vienna":"Wien",
    "Africa/Algiers":"Alger",
    "Europe/Bucharest":"Bukarest",
    "Africa/Cairo":"Kairo",
    "Europe/Helsinki":"Helsingfors",
    "Europe/Kiev":"Kiev",
    "Europe/Riga":"Riga",
    "Europe/Sofia":"Sofia",
    "Europe/Tallinn":"Tallin",
    "Europe/Vilnius":"Vilnius",
    "Europe/Athens":"Aten",
    "Europe/Istanbul":"Istanbul",
    "Europe/Minsk":"Minsk",
    "Asia/Jerusalem":"Jerusalem",
    "Africa/Harare":"Harare",
    "Africa/Johannesburg":"Johannesburg",
    "Europe/Volgograd":"Volgograd",
    "Europe/Moscow":"Moskva",
    "Asia/Kuwait":"Kuwait",
    "Asia/Riyadh":"Riyadh",
    "Africa/Nairobi":"Nairobi",
    "Asia/Baghdad":"Bagdad",
    "Asia/Tehran":"Teheran",
    "Asia/Muscat":"Muskat",
    "Asia/Baku":"Baku",
    "Asia/Tbilisi":"Tbilisi",
    "Asia/Yerevan":"Jerevan",
    "Asia/Kabul":"Kabul",
    "Asia/Yekaterinburg":"Jekaterinburg",
    "Asia/Karachi":"Karachi",
    "Asia/Tashkent":"Tasjkent",
    "Asia/Calcutta":"Kolkata",
    "Asia/Kathmandu":"Kathmandu",
    "Asia/Dhaka":"Dacca",
    "Asia/Colombo":"Colombo",
    "Asia/Almaty":"Alma-Ata",
    "Asia/Novosibirsk":"Novosibirsk",
    "Asia/Rangoon":"Rangoon",
    "Asia/Bangkok":"Bangkok",
    "Asia/Jakarta":"Jakarta",
    "Asia/Krasnoyarsk":"Krasnojarsk",
    "Asia/Shanghai":"Shanghai",
    "Asia/Chongqing":"Chongqing",
    "Asia/Hong_Kong":"Hongkong",
    "Asia/Urumqi":"Urumqi",
    "Asia/Kuala_Lumpur":"Kuala Lumpur",
    "Asia/Singapore":"Singapore",
    "Asia/Taipei":"Taipei",
    "Australia/Perth":"Perth",
    "Asia/Irkutsk":"Irkutsk",
    "Asia/Ulaanbaatar":"Ulan Bator",
    "Asia/Seoul":"Söul",
    "Asia/Tokyo":"Tokyo",
    "Asia/Yakutsk":"Jakutsk",
    "Australia/Darwin":"Darwin",
    "Australia/Adelaide":"Adelaide",
    "Australia/Melbourne":"Melbourne",
    "Australia/Sydney":"Sydney",
    "Australia/Brisbane":"Brisbane",
    "Australia/Hobart":"Hobart",
    "Asia/Vladivostok":"Vladivostok",
    "Pacific/Guam":"Guam",
    "Pacific/Port_Moresby":"Port Moresby",
    "Asia/Magadan":"Magadan",
    "Pacific/Noumea":"Noumea",
    "Pacific/Fiji":"Fiji",
    "Asia/Kamchatka":"Kamtjatka",
    "Pacific/Majuro":"Majuro",
    "Pacific/Auckland":"Auckland",
    "Pacific/Tongatapu":"Tongatapu"
}