{
    "Pacific/Midway":"Midway",
    "Pacific/Pago_Pago":"Pago Pago",
    "Pacific/Honolulu":"Honolulu",
    "America/Juneau":"Juneau",
    "America/Los_Angeles":"Los Angeles",
    "America/Tijuana":"Tijuana",
    "America/Denver":"Denver",
    "America/Phoenix":"Phoenix",
    "America/Chihuahua":"Chihuahua",
    "America/Mazatlan":"Mazatlan",
    "America/Chicago":"Chicago",
    "America/Regina":"Regina",
    "America/Mexico_City":"Meksiko City",
    "America/Monterrey":"Monterrey",
    "America/Guatemala":"Guatemala",
    "America/New_York":"New York",
    "America/Indiana/Indianapolis":"Indianapolis, Indiana",
    "America/Bogota":"Bogota",
    "America/Lima":"Lima",
    "America/Halifax":"Halifax",
    "America/Caracas":"Karakas",
    "America/La_Paz":"La Paz",
    "America/Santiago":"Santiago",
    "America/St_Johns":"St. John’s",
    "America/Sao_Paulo":"Sao Paulo",
    "America/Argentina/Buenos_Aires":"Buenos Aires, Argentina",
    "America/Guyana":"Guyana",
    "America/Godthab":"Godthab",
    "Atlantic/South_Georgia":"Güney Georgia",
    "Atlantic/Azores":"Azor Adaları",
    "Atlantic/Cape_Verde":"Cape Verde",
    "Europe/Dublin":"Dublin",
    "Europe/London":"Londra",
    "Europe/Lisbon":"Lizbon",
    "Africa/Casablanca":"Kazablanka",
    "Africa/Monrovia":"Monrovia",
    "Etc/UTC":"UTC",
    "Europe/Belgrade":"Belgrad",
    "Europe/Bratislava":"Bratislava",
    "Europe/Budapest":"Budapeşte",
    "Europe/Ljubljana":"Ljubljana",
    "Europe/Prague":"Prag",
    "Europe/Sarajevo":"Saraybosna",
    "Europe/Skopje":"Üsküp",
    "Europe/Warsaw":"Varşova",
    "Europe/Zagreb":"Zagreb",
    "Europe/Brussels":"Brüksel",
    "Europe/Copenhagen":"Kopenhag",
    "Europe/Madrid":"Madrid",
    "Europe/Paris":"Paris",
    "Europe/Amsterdam":"Amsterdam",
    "Europe/Berlin":"Berlin",
    "Europe/Rome":"Roma",
    "Europe/Stockholm":"Stokholm",
    "Europe/Vienna":"Viyana",
    "Africa/Algiers":"Cezayir",
    "Europe/Bucharest":"Bükreş",
    "Africa/Cairo":"Kahire",
    "Europe/Helsinki":"Helsinki",
    "Europe/Kiev":"Kiev",
    "Europe/Riga":"Riga",
    "Europe/Sofia":"Sofya",
    "Europe/Tallinn":"Tallinn",
    "Europe/Vilnius":"Vilnius",
    "Europe/Athens":"Atina",
    "Europe/Istanbul":"İstanbul",
    "Europe/Minsk":"Minsk",
    "Asia/Jerusalem":"Kudüs",
    "Africa/Harare":"Harare",
    "Africa/Johannesburg":"Johannesburg",
    "Europe/Volgograd":"Volgograd",
    "Europe/Moscow":"Moskova",
    "Asia/Kuwait":"Kuveyt",
    "Asia/Riyadh":"Riyad",
    "Africa/Nairobi":"Nairobi",
    "Asia/Baghdad":"Bağdat",
    "Asia/Tehran":"Tahran",
    "Asia/Muscat":"Maskat",
    "Asia/Baku":"Bakü",
    "Asia/Tbilisi":"Tiflis",
    "Asia/Yerevan":"Erivan",
    "Asia/Kabul":"Kabil",
    "Asia/Yekaterinburg":"Yekaterinburg",
    "Asia/Karachi":"Karaçi",
    "Asia/Tashkent":"Taşkent",
    "Asia/Calcutta":"Kolkata",
    "Asia/Kathmandu":"Kathmandu",
    "Asia/Dhaka":"Dakka",
    "Asia/Colombo":"Kolombo",
    "Asia/Almaty":"Almatı",
    "Asia/Novosibirsk":"Novosibirsk",
    "Asia/Rangoon":"Yangon",
    "Asia/Bangkok":"Bangkok",
    "Asia/Jakarta":"Cakarta",
    "Asia/Krasnoyarsk":"Krasnoyarsk",
    "Asia/Shanghai":"Şangay",
    "Asia/Chongqing":"Çunking",
    "Asia/Hong_Kong":"Hong Kong",
    "Asia/Urumqi":"Urumçi",
    "Asia/Kuala_Lumpur":"Kuala Lumpur",
    "Asia/Singapore":"Singapur",
    "Asia/Taipei":"Taipei",
    "Australia/Perth":"Perth",
    "Asia/Irkutsk":"İrkutsk",
    "Asia/Ulaanbaatar":"Ulan Batur",
    "Asia/Seoul":"Seul",
    "Asia/Tokyo":"Tokyo",
    "Asia/Yakutsk":"Yakutsk",
    "Australia/Darwin":"Darwin",
    "Australia/Adelaide":"Adelaide",
    "Australia/Melbourne":"Melbourne",
    "Australia/Sydney":"Sidney",
    "Australia/Brisbane":"Brisbane",
    "Australia/Hobart":"Hobart",
    "Asia/Vladivostok":"Vladivostok",
    "Pacific/Guam":"Guam",
    "Pacific/Port_Moresby":"Port Moresby",
    "Asia/Magadan":"Magadan",
    "Pacific/Noumea":"Noumea",
    "Pacific/Fiji":"Fiji",
    "Asia/Kamchatka":"Kamçatka",
    "Pacific/Majuro":"Majuro",
    "Pacific/Auckland":"Auckland",
    "Pacific/Tongatapu":"Tongatapu"
}