{
    "Pacific/Midway":"وسط دن",
    "Pacific/Pago_Pago":"پاگو پاگو",
    "Pacific/Honolulu":"ہونولولو",
    "America/Juneau":"جونیئو",
    "America/Los_Angeles":"لاس اینجلس",
    "America/Tijuana":"تیجوآنا",
    "America/Denver":"ڈینور",
    "America/Phoenix":"فینکس",
    "America/Chihuahua":"چیہوآہوآ",
    "America/Mazatlan":"میزٹلان",
    "America/Chicago":"شکاگو",
    "America/Regina":"ریجینا",
    "America/Mexico_City":"میکسیکو سٹی",
    "America/Monterrey":"مونٹیری",
    "America/Guatemala":"گواٹے مالا",
    "America/New_York":"نیو یارک",
    "America/Indiana/Indianapolis":"Indianapolis, Indiana",
    "America/Bogota":"بگوٹا",
    "America/Lima":"لیما",
    "America/Halifax":"ہیلیفیکس",
    "America/Caracas":"کراکاس",
    "America/La_Paz":"لا پاز",
    "America/Santiago":"سنٹیاگو",
    "America/St_Johns":"St. John’s",
    "America/Sao_Paulo":"ساؤ پالو",
    "America/Argentina/Buenos_Aires":"Buenos Aires, Argentina",
    "America/Guyana":"گیانا",
    "America/Godthab":"گاڈتھیب",
    "Atlantic/South_Georgia":"جنوبی جارجیا",
    "Atlantic/Azores":"ازوریس",
    "Atlantic/Cape_Verde":"کیپ ورڈی",
    "Europe/Dublin":"ڈبلن",
    "Europe/London":"لندن",
    "Europe/Lisbon":"لسبن",
    "Africa/Casablanca":"کیسا بلانکا",
    "Africa/Monrovia":"مونروویا",
    "Etc/UTC":"UTC",
    "Europe/Belgrade":"بلغراد",
    "Europe/Bratislava":"بریٹِسلاوا",
    "Europe/Budapest":"بدھاپیسٹ",
    "Europe/Ljubljana":"جبجانا",
    "Europe/Prague":"پراگ",
    "Europe/Sarajevo":"سراجیوو",
    "Europe/Skopje":"اسکوپجے",
    "Europe/Warsaw":"وارسا",
    "Europe/Zagreb":"زیگریب",
    "Europe/Brussels":"برسلز",
    "Europe/Copenhagen":"کوپن ہیگن",
    "Europe/Madrid":"میڈرڈ",
    "Europe/Paris":"پیرس",
    "Europe/Amsterdam":"ایمسٹرڈم",
    "Europe/Berlin":"برلن",
    "Europe/Rome":"روم",
    "Europe/Stockholm":"اسٹاک ہوم",
    "Europe/Vienna":"ویانا",
    "Africa/Algiers":"الجیئرس",
    "Europe/Bucharest":"بخارسٹ",
    "Africa/Cairo":"قاہرہ",
    "Europe/Helsinki":"ہیلسنکی",
    "Europe/Kiev":"کیوو",
    "Europe/Riga":"ریگا",
    "Europe/Sofia":"صوفیہ",
    "Europe/Tallinn":"تالِّن",
    "Europe/Vilnius":"وِلنیئس",
    "Europe/Athens":"ایتھنز",
    "Europe/Istanbul":"استنبول",
    "Europe/Minsk":"مِنسک",
    "Asia/Jerusalem":"یروشلم",
    "Africa/Harare":"ہرارے",
    "Africa/Johannesburg":"جوہانسبرگ",
    "Europe/Volgograd":"وولگوگراد",
    "Europe/Moscow":"ماسکو",
    "Asia/Kuwait":"کویت",
    "Asia/Riyadh":"ریاض",
    "Africa/Nairobi":"نیروبی",
    "Asia/Baghdad":"بغداد",
    "Asia/Tehran":"تہران",
    "Asia/Muscat":"مسقط",
    "Asia/Baku":"باکو",
    "Asia/Tbilisi":"طبلیسی",
    "Asia/Yerevan":"یریوان",
    "Asia/Kabul":"کابل",
    "Asia/Yekaterinburg":"یکاٹیرِنبرگ",
    "Asia/Karachi":"کراچی",
    "Asia/Tashkent":"تاشقند",
    "Asia/Calcutta":"Kolkata",
    "Asia/Kathmandu":"Kathmandu",
    "Asia/Dhaka":"ڈھاکہ",
    "Asia/Colombo":"کولمبو",
    "Asia/Almaty":"الماٹی",
    "Asia/Novosibirsk":"نوووسِبِرسک",
    "Asia/Rangoon":"رنگون",
    "Asia/Bangkok":"بنکاک",
    "Asia/Jakarta":"جکارتہ",
    "Asia/Krasnoyarsk":"کریسنویارسک",
    "Asia/Shanghai":"شنگھائی",
    "Asia/Chongqing":"چانگ کنگ",
    "Asia/Hong_Kong":"ہانگ کانگ",
    "Asia/Urumqi":"یورومکی",
    "Asia/Kuala_Lumpur":"کوالا لمپور",
    "Asia/Singapore":"سنگاپور",
    "Asia/Taipei":"تائپے",
    "Australia/Perth":"پرتھ",
    "Asia/Irkutsk":"ارکتسک",
    "Asia/Ulaanbaatar":"اولان باتار",
    "Asia/Seoul":"سیئول",
    "Asia/Tokyo":"ٹوکیو",
    "Asia/Yakutsk":"یکوتسک",
    "Australia/Darwin":"ڈارون",
    "Australia/Adelaide":"اڈیلائڈ",
    "Australia/Melbourne":"ملبورن",
    "Australia/Sydney":"سڈنی",
    "Australia/Brisbane":"برسبین",
    "Australia/Hobart":"ہوبارٹ",
    "Asia/Vladivostok":"ولادی ووستک",
    "Pacific/Guam":"گوآم",
    "Pacific/Port_Moresby":"پورٹ موریسبی",
    "Asia/Magadan":"میگیدن",
    "Pacific/Noumea":"نؤمیا",
    "Pacific/Fiji":"فجی",
    "Asia/Kamchatka":"کیمچٹکا",
    "Pacific/Majuro":"مجورو",
    "Pacific/Auckland":"آکلینڈ",
    "Pacific/Tongatapu":"ٹونگاٹاپو"
}